window.CHARA_SABUN_I18N = {
  ja: {
    "meta.title": "キャラ差分管理ツール | TRPG WEBツール観測所",
    "meta.description": "TRPG立ち絵・表情差分の画像確認、ファイル名整理、CCFOLIA向け@差分チャットパレット作成を支援するWebツールです。",
    "app.eyebrow": "TRPG WEBツール観測所", "app.title": "キャラ差分管理ツール",
    "app.lead": "立ち絵・表情差分をまとめて確認し、ファイル名を整えて、CCFOLIA向けの <strong>@差分</strong> チャットパレットを生成します。",
    "aria.header": "ヘッダー操作", "aria.x": "Xに投稿", "language.select": "表示言語を選択",
    "nav.back": "←TRPG WEBツール観測所", "button.usage": "使い方", "button.shortcuts": "ショートカット", "button.reset": "リセット",
    "usage.title": "使い方", "usage.step1": "画像をドラッグ&ドロップ、またはクリックして複数画像を選択します。", "usage.step2": "メインファイル名を入力し、各サムネイル横の差分名を編集します。", "usage.step3": "必要に応じて「番号追加」をONにすると、<code>メインファイル名01_差分名.png</code> の形式になります。", "usage.step4": "「画像をZIPでダウンロード」で画像一式を保存できます。", "usage.step5": "「@差分チャパレをコピー」で、CCFOLIAなどに貼り付ける差分切替用チャットパレットをコピーできます。",
    "shortcuts.title": "ショートカット", "shortcuts.open": "画像ファイルを選択", "shortcuts.zip": "ZIP出力", "shortcuts.copy": "@差分チャパレをコピー", "shortcuts.number": "番号追加 ON / OFF", "shortcuts.escape": "使い方 / ショートカットを閉じる。未展開時はリセット（確認ダイアログを表示）",
    "upload.title": "画像アップロード", "upload.drop": "<strong>PNG / JPG / WEBP</strong> をドラッグ&ドロップ", "upload.click": "またはクリックして複数ファイルを選択", "upload.mainName": "メインファイル名", "upload.mainPlaceholder": "例：hanabishi_hibana", "upload.help": "出力名は <code>メインファイル名_差分名.png</code> になります。",
    "thumb.title": "サムネイル一覧", "thumb.number": "番号追加", "thumb.clickPreview": "クリックで大きく表示", "thumb.empty": "画像を追加すると、ここにサムネイルと差分名入力欄が表示されます。", "thumb.select": "{name}を選択", "thumb.preview": "{name}をプレビュー", "thumb.name": "差分名",
    "preview.title": "大プレビュー", "preview.alt": "選択中の差分プレビュー", "preview.filename": "出力ファイル名：{name}", "preview.unset": "未入力", "preview.suggestions": "差分名サジェスト",
    "output.title": "出力", "output.download": "画像をZIPでダウンロード", "output.copy": "@差分チャパレをコピー", "output.palette": "生成されるチャットパレット",
    "status.initial": "画像を読み込んでください。", "status.number": "番号追加を{state}にしました。", "status.selectFirst": "先に画像を選択してください。", "status.noImages": "画像ファイルが見つかりませんでした。", "status.added": "{count}件の画像を追加しました。", "status.reordered": "サムネイルの順番を変更しました。", "status.zipLibrary": "ZIP出力ライブラリを読み込めませんでした。ネット接続を確認してください。", "status.zipCreating": "ZIPを生成しています。", "status.zipStarted": "画像ZIPのダウンロードを開始しました。", "status.zipDone": "画像ZIPのダウンロードが完了しました。", "status.zipFailed": "ZIP出力に失敗しました。", "status.copied": "@差分チャットパレットをコピーしました。", "status.copyManual": "コピーを実行しました。うまくいかない場合はテキスト欄から手動コピーしてください。", "status.resetConfirm": "すべての画像・差分名・入力内容をリセットします。よろしいですか？", "status.reset": "リセットしました。", "status.downloadDone": "ダウンロードが完了しました。", "fallback.variant": "差分{number}",
    "footer.note": "<strong>利用上の注意</strong> 本ツールは、開発者 <a href=\"https://x.com/KumachanSteps\" target=\"_blank\" rel=\"noopener noreferrer\">@KumachanSteps</a> による個人制作の非公式TRPG支援ツールです。各TRPGシステム、シナリオ、外部サービスの利用規約・権利表記については、利用者自身でご確認ください。 不具合報告や要望は、Xの <a href=\"https://x.com/KumachanSteps\" target=\"_blank\" rel=\"noopener noreferrer\">@KumachanSteps</a> 宛のDMにてお送りください。ただし、すべての報告や要望に返信・対応できるとは限りません。"
  },
  en: {
    "meta.title": "Character Variant Manager | TRPG Web Tools Observatory", "meta.description": "Review TRPG character images and expression variants, organize filenames, and create @variant chat palettes for CCFOLIA.",
    "app.eyebrow": "TRPG Web Tools Observatory", "app.title": "Character Variant Manager", "app.lead": "Review character and expression variants together, organize filenames, and generate a CCFOLIA <strong>@variant</strong> chat palette.",
    "aria.header": "Header actions", "aria.x": "Post on X", "language.select": "Select display language", "nav.back": "← TRPG Web Tools Observatory", "button.usage": "How to Use", "button.shortcuts": "Shortcuts", "button.reset": "Reset",
    "usage.title": "How to Use", "usage.step1": "Drag and drop images, or click to select multiple images.", "usage.step2": "Enter the main filename and edit the variant name beside each thumbnail.", "usage.step3": "Turn on Numbering if needed to use the format <code>mainname01_variant.png</code>.", "usage.step4": "Save all images with Download Images as ZIP.", "usage.step5": "Use Copy @variant Palette to copy a variant-switching chat palette for CCFOLIA and similar services.",
    "shortcuts.title": "Shortcuts", "shortcuts.open": "Choose image files", "shortcuts.zip": "Export ZIP", "shortcuts.copy": "Copy @variant palette", "shortcuts.number": "Toggle numbering", "shortcuts.escape": "Close How to Use / Shortcuts. If closed, show the reset confirmation.",
    "upload.title": "Upload Images", "upload.drop": "Drag and drop <strong>PNG / JPG / WEBP</strong>", "upload.click": "or click to select multiple files", "upload.mainName": "Main filename", "upload.mainPlaceholder": "Example: hanabishi_hibana", "upload.help": "Output names use <code>mainname_variant.png</code>.",
    "thumb.title": "Thumbnails", "thumb.number": "Add numbers", "thumb.clickPreview": "Click to enlarge", "thumb.empty": "Add images to display thumbnails and variant-name fields here.", "thumb.select": "Select {name}", "thumb.preview": "Preview {name}", "thumb.name": "Variant name",
    "preview.title": "Large Preview", "preview.alt": "Selected variant preview", "preview.filename": "Output filename: {name}", "preview.unset": "Not entered", "preview.suggestions": "Variant Suggestions",
    "output.title": "Output", "output.download": "Download Images as ZIP", "output.copy": "Copy @variant Palette", "output.palette": "Generated Chat Palette",
    "status.initial": "Load some images to begin.", "status.number": "Numbering is now {state}.", "status.selectFirst": "Select an image first.", "status.noImages": "No image files were found.", "status.added": "Added {count} image(s).", "status.reordered": "Changed the thumbnail order.", "status.zipLibrary": "Could not load the ZIP library. Check your internet connection.", "status.zipCreating": "Creating ZIP.", "status.zipStarted": "Started downloading the image ZIP.", "status.zipDone": "Image ZIP download completed.", "status.zipFailed": "ZIP export failed.", "status.copied": "Copied the @variant chat palette.", "status.copyManual": "Copy was attempted. If it failed, copy manually from the text field.", "status.resetConfirm": "Reset all images, variant names, and input?", "status.reset": "Reset complete.", "status.downloadDone": "Download completed.", "fallback.variant": "variant{number}",
    "footer.note": "<strong>Important Notes</strong> This is an unofficial personal TRPG support tool created by <a href=\"https://x.com/KumachanSteps\" target=\"_blank\" rel=\"noopener noreferrer\">@KumachanSteps</a>. Please check the terms, licenses, and rights notices for each TRPG system, scenario, and external service. Send bug reports or requests by DM on X; replies or fixes cannot be guaranteed."
  },
  ko: {
    "meta.title": "캐릭터 차분 관리 도구 | TRPG 웹 도구 관측소", "meta.description": "TRPG 캐릭터 이미지와 표정 차분을 확인하고 파일명을 정리하며 CCFOLIA용 @차분 채팅 팔레트를 만드는 웹 도구입니다.",
    "app.eyebrow": "TRPG 웹 도구 관측소", "app.title": "캐릭터 차분 관리 도구", "app.lead": "캐릭터 이미지와 표정 차분을 한꺼번에 확인하고 파일명을 정리해 CCFOLIA용 <strong>@차분</strong> 채팅 팔레트를 생성합니다.",
    "aria.header": "헤더 작업", "aria.x": "X에 게시", "language.select": "표시 언어 선택", "nav.back": "← TRPG 웹 도구 관측소", "button.usage": "사용 방법", "button.shortcuts": "단축키", "button.reset": "초기화",
    "usage.title": "사용 방법", "usage.step1": "이미지를 드래그 앤 드롭하거나 클릭하여 여러 이미지를 선택합니다.", "usage.step2": "기본 파일명을 입력하고 각 썸네일 옆의 차분명을 편집합니다.", "usage.step3": "필요하면 ‘번호 추가’를 켜서 <code>기본파일명01_차분명.png</code> 형식으로 만듭니다.", "usage.step4": "‘이미지를 ZIP으로 다운로드’로 이미지 전체를 저장할 수 있습니다.", "usage.step5": "‘@차분 팔레트 복사’로 CCFOLIA 등에 붙여넣을 차분 전환용 채팅 팔레트를 복사할 수 있습니다.",
    "shortcuts.title": "단축키", "shortcuts.open": "이미지 파일 선택", "shortcuts.zip": "ZIP 출력", "shortcuts.copy": "@차분 팔레트 복사", "shortcuts.number": "번호 추가 켜기/끄기", "shortcuts.escape": "사용 방법 / 단축키를 닫습니다. 둘 다 닫힌 상태에서는 초기화 확인창을 표시합니다.",
    "upload.title": "이미지 업로드", "upload.drop": "<strong>PNG / JPG / WEBP</strong>를 드래그 앤 드롭", "upload.click": "또는 클릭하여 여러 파일 선택", "upload.mainName": "기본 파일명", "upload.mainPlaceholder": "예: hanabishi_hibana", "upload.help": "출력 이름은 <code>기본파일명_차분명.png</code> 형식입니다.",
    "thumb.title": "썸네일 목록", "thumb.number": "번호 추가", "thumb.clickPreview": "클릭하여 크게 보기", "thumb.empty": "이미지를 추가하면 여기에 썸네일과 차분명 입력란이 표시됩니다.", "thumb.select": "{name} 선택", "thumb.preview": "{name} 미리보기", "thumb.name": "차분명",
    "preview.title": "큰 미리보기", "preview.alt": "선택한 차분 미리보기", "preview.filename": "출력 파일명: {name}", "preview.unset": "미입력", "preview.suggestions": "차분명 추천",
    "output.title": "출력", "output.download": "이미지를 ZIP으로 다운로드", "output.copy": "@차분 팔레트 복사", "output.palette": "생성되는 채팅 팔레트",
    "status.initial": "이미지를 불러와 주세요.", "status.number": "번호 추가를 {state} 상태로 변경했습니다.", "status.selectFirst": "먼저 이미지를 선택해 주세요.", "status.noImages": "이미지 파일을 찾지 못했습니다.", "status.added": "이미지 {count}개를 추가했습니다.", "status.reordered": "썸네일 순서를 변경했습니다.", "status.zipLibrary": "ZIP 출력 라이브러리를 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.", "status.zipCreating": "ZIP을 생성하고 있습니다.", "status.zipStarted": "이미지 ZIP 다운로드를 시작했습니다.", "status.zipDone": "이미지 ZIP 다운로드가 완료되었습니다.", "status.zipFailed": "ZIP 출력에 실패했습니다.", "status.copied": "@차분 채팅 팔레트를 복사했습니다.", "status.copyManual": "복사를 시도했습니다. 실패했다면 텍스트 영역에서 직접 복사해 주세요.", "status.resetConfirm": "모든 이미지, 차분명과 입력 내용을 초기화하시겠습니까?", "status.reset": "초기화했습니다.", "status.downloadDone": "다운로드가 완료되었습니다.", "fallback.variant": "차분{number}",
    "footer.note": "<strong>이용 시 주의사항</strong> 이 도구는 개발자 <a href=\"https://x.com/KumachanSteps\" target=\"_blank\" rel=\"noopener noreferrer\">@KumachanSteps</a>가 개인적으로 제작한 비공식 TRPG 지원 도구입니다. 각 TRPG 시스템, 시나리오, 외부 서비스의 이용 약관과 권리 표시는 이용자가 직접 확인해 주세요. 오류 신고나 요청은 X의 DM으로 보내 주세요. 모든 신고와 요청에 답변하거나 대응하지 못할 수 있습니다."
  }
};
