(function(){
const STORAGE_KEY="trpg-chara-libra-v1";let characters=[];let currentId="";
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const memoLabels={profile:"プロフィール",items:"持ち物",combat:"戦闘メモ",relationships:"人間関係",scenarios:"通過シナリオ",free:"自由メモ",secret:"秘匿メモ"};
function load(){try{characters=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");}catch{characters=[];}}
function saveStore(){localStorage.setItem(STORAGE_KEY,JSON.stringify(characters));}
function fmt(d){return d?new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(d)):"未取込";}
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200);}
function findMatch(c){return characters.find(x=>(c.externalUrl&&x.externalUrl===c.externalUrl)||x.name===c.name);}
function mergeCharacter(old,c){return {...old,...c,id:old.id,timestamps:{...old.timestamps,updatedAt:new Date().toISOString(),ccfoliaImportedAt:new Date().toISOString(),iacharaImportedAt:c.timestamps.iacharaImportedAt||old.timestamps.iacharaImportedAt},source:{ccfoliaRaw:c.source.ccfoliaRaw,iacharaText:c.source.iacharaText||old.source?.iacharaText||""}};}
function importCcf(){try{const c=CharaLibraParser.fromCcf($("ccfoliaInput").value,$("iacharaInput").value);const targetId=$("updateTarget").value;const idx=targetId?characters.findIndex(x=>x.id===targetId):characters.findIndex(x=>x.id===(findMatch(c)||{}).id);if(idx>=0){characters[idx]=mergeCharacter(characters[idx],c);currentId=characters[idx].id;toast("既存キャラクターを更新しました");}else{characters.unshift(c);currentId=c.id;toast("キャラクターを登録しました");}saveStore();renderLibrary();showDetail(currentId);$("ccfoliaInput").value="";}catch(e){toast("JSON解析に失敗しました: "+e.message);}}
function filtered(){let arr=[...characters];const q=$("keywordFilter").value.trim().toLowerCase(),sys=$("systemFilter").value.trim().toLowerCase(),st=$("statusFilter").value,tag=$("tagFilter").value.trim().toLowerCase();arr=arr.filter(c=>{const hay=[c.name,c.reading,c.system,c.edition,c.occupation,(c.tags||[]).join(" "),c.commands].join(" ").toLowerCase();return (!q||hay.includes(q))&&(!sys||String(c.system).toLowerCase().includes(sys)||String(c.edition).toLowerCase().includes(sys))&&(!st||c.lifeStatus===st)&&(!tag||(c.tags||[]).join(" ").toLowerCase().includes(tag));});const stat=(c,k)=>Number(c.stats?.[k]?.value??c.stats?.[k]??0);const sort=$("sortSelect").value;arr.sort((a,b)=>sort==="updatedAsc"?new Date(a.timestamps.updatedAt)-new Date(b.timestamps.updatedAt):sort==="nameAsc"?a.name.localeCompare(b.name,"ja"):sort==="createdDesc"?new Date(b.timestamps.createdAt)-new Date(a.timestamps.createdAt):sort==="sanDesc"?stat(b,"SAN")-stat(a,"SAN"):sort==="sanAsc"?stat(a,"SAN")-stat(b,"SAN"):sort==="hpDesc"?stat(b,"HP")-stat(a,"HP"):sort==="skillDesc"?(b.skills||[]).length-(a.skills||[]).length:new Date(b.timestamps.updatedAt)-new Date(a.timestamps.updatedAt));return arr;}
function renderLibrary(){const grid=$("cardGrid");const arr=filtered();$("countBadge").textContent=arr.length;$("updateTarget").innerHTML='<option value="">新規登録 / 自動判定</option>'+characters.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join("");grid.innerHTML=arr.length?arr.map(c=>{const hp=c.stats?.HP?.value??"-",mp=c.stats?.MP?.value??"-",san=c.stats?.SAN?.value??"-";return `<article class="character-card" data-id="${esc(c.id)}"><div class="card-main"><img class="card-icon" src="${esc(c.iconUrl)}" alt="" onerror="this.style.display='none'"><div><div class="card-name">${esc(c.name)}</div><div class="meta">${esc([c.system,c.edition].filter(Boolean).join(" / ")||"System未設定")}<br>${esc(c.occupation||"職業未設定")} / ${esc(CharaLibraLanguage.life(c.lifeStatus))}</div></div></div><p>HP ${esc(hp)} / MP ${esc(mp)} / SAN ${esc(san)}</p><div>${(c.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div><p class="meta">Updated: ${esc(fmt(c.timestamps.updatedAt))}<br>CCFOLIA: ${esc(fmt(c.timestamps.ccfoliaImportedAt))}<br>いあきゃら: ${esc(fmt(c.timestamps.iacharaImportedAt))}</p></article>`}).join(""):'<p class="hint">まだ登録キャラクターがありません。</p>';grid.querySelectorAll(".character-card").forEach(el=>el.onclick=()=>showDetail(el.dataset.id));}
function current(){return characters.find(c=>c.id===currentId);}
function showDetail(id){currentId=id;const c=current();if(!c)return;$("libraryView").classList.add("hidden");$("detailView").classList.remove("hidden");["name","reading","system","edition","occupation"].forEach(k=>$(k+"Input").value=c[k]||"");$("lifeStatusInput").value=c.lifeStatus||"alive";$("tagsInput").value=(c.tags||[]).join(", ");$("tachieInput").value=c.tachieUrl||"";$("iconInput").value=c.iconUrl||"";$("externalInput").value=c.externalUrl||"";$("detailIcon").src=c.iconUrl||"";$("commandsInput").value=c.commands||"";$("freshnessBox").innerHTML=`最終編集：${esc(fmt(c.timestamps.updatedAt))}<br>CCFOLIA JSON取込：${esc(fmt(c.timestamps.ccfoliaImportedAt))}<br>いあきゃらTXT取込：${esc(fmt(c.timestamps.iacharaImportedAt))}`;renderStats(c);renderSkills(c);renderMemo(c);}
function renderStats(c){$("statsGrid").innerHTML=CharaLibraParser.STAT_KEYS.map(k=>{const v=c.stats?.[k];const text=v&&typeof v==="object"?`${v.value}/${v.max}`:(v??"-");return `<div class="stat-box"><b>${esc(k)}</b>${esc(text)}</div>`}).join("");}
function renderSkills(c){const q=($("skillSearch").value||"").toLowerCase();$("skillsList").innerHTML=(c.skills||[]).filter(s=>!q||s.name.toLowerCase().includes(q)).map(s=>`<div class="skill"><span>${esc(s.name)}</span><b>${esc(s.value)}</b></div>`).join("")||'<p class="hint">技能が抽出されていません。</p>';}
function renderMemo(c){$("memoEditors").innerHTML=Object.keys(memoLabels).map(k=>`<label class="memo-row"><input type="checkbox" data-memo-opt="${k}" ${c.memoExportOptions?.[k]?"checked":""}> <b>${memoLabels[k]}を出力</b><textarea data-memo-key="${k}">${esc(c.memoSections?.[k]||"")}</textarea></label>`).join("");}
function collectDetail(){const c=current();if(!c)return null;["name","reading","system","edition","occupation"].forEach(k=>c[k]=$(k+"Input").value.trim());c.lifeStatus=$("lifeStatusInput").value;c.tags=$("tagsInput").value.split(/[、,]/).map(s=>s.trim()).filter(Boolean);c.tachieUrl=$("tachieInput").value.trim();c.iconUrl=$("iconInput").value.trim();c.externalUrl=$("externalInput").value.trim();c.commands=$("commandsInput").value;c.skills=CharaLibraParser.extractSkills(c.commands);c.memoSections={};document.querySelectorAll("[data-memo-key]").forEach(el=>c.memoSections[el.dataset.memoKey]=el.value);c.memoExportOptions={};document.querySelectorAll("[data-memo-opt]").forEach(el=>c.memoExportOptions[el.dataset.memoOpt]=el.checked);c.timestamps.updatedAt=new Date().toISOString();return c;}
function saveDetail(){if(!currentId)return;collectDetail();saveStore();renderLibrary();showDetail(currentId);toast("保存しました");}
function buildMemo(c){return Object.keys(memoLabels).filter(k=>c.memoExportOptions?.[k]).map(k=>c.memoSections?.[k]?`【${memoLabels[k]}】\n${c.memoSections[k]}`:"").filter(Boolean).join("\n\n");}
function buildCcf(c){return JSON.stringify({name:c.name,initiative:c.initiative||0,externalUrl:c.externalUrl||"",iconUrl:c.iconUrl||"",commands:c.commands||"",memo:buildMemo(c),status:Object.entries(c.stats||{}).filter(([,v])=>v&&typeof v==="object").map(([label,v])=>({label,value:v.value,max:v.max})),params:Object.entries(c.stats||{}).filter(([,v])=>!v||typeof v!=="object").map(([label,value])=>({label,value:String(value??"")}))},null,2);}
async function copyCcf(){const c=collectDetail();saveStore();const out=buildCcf(c);try{await navigator.clipboard.writeText(out);toast("CCFOLIA駒データをコピーしました");$("manualCopyNotice").classList.add("hidden");$("manualCopyArea").classList.add("hidden");}catch{$("manualCopyNotice").classList.remove("hidden");$("manualCopyArea").classList.remove("hidden");$("manualCopyArea").value=out;}}
function download(name,text){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"application/json"}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
function init(){load();renderLibrary();$("importBtn").onclick=importCcf;["keywordFilter","systemFilter","statusFilter","tagFilter","sortSelect"].forEach(id=>$(id).oninput=renderLibrary);$("backBtn").onclick=()=>{$("detailView").classList.add("hidden");$("libraryView").classList.remove("hidden");renderLibrary();};$("saveDetailBtn").onclick=saveDetail;$("copyCcfBtn").onclick=copyCcf;$("copyCommandsBtn").onclick=async()=>{await navigator.clipboard.writeText($("commandsInput").value);toast("チャットパレットをコピーしました");};$("skillSearch").oninput=()=>renderSkills(current());$("exportAllBtn").onclick=()=>download("chara-libra-backup.json",JSON.stringify(characters,null,2));$("exportOneBtn").onclick=()=>download(`${current().name||"character"}.json`,JSON.stringify(current(),null,2));$("deleteBtn").onclick=()=>{if(confirm("削除しますか？")){characters=characters.filter(c=>c.id!==currentId);saveStore();$("backBtn").click();}};$("importAllFile").onchange=e=>{const f=e.target.files[0];if(!f)return;f.text().then(t=>{characters=JSON.parse(t);saveStore();renderLibrary();toast("インポートしました");});};$("themeBtn").onclick=()=>document.body.classList.toggle("light");$("langBtn").onclick=()=>{CharaLibraLanguage.toggle();renderLibrary();};$("xShareBtn").onclick=()=>open("https://twitter.com/intent/tweet?text="+encodeURIComponent("Chara-Libra｜TRPG WEBツール観測所 でキャラクター情報を管理しました！")+"&url="+encodeURIComponent("https://kumachansteps.github.io/trpg-web-tools/tools/chara-libra-tool/"),"_blank","noopener");["usageBtn","shortcutBtn"].forEach(id=>$(id).onclick=()=>$(id==="usageBtn"?"usagePanel":"shortcutPanel").classList.toggle("open"));document.querySelectorAll("[data-close-panel]").forEach(b=>b.onclick=()=>$(b.dataset.closePanel).classList.remove("open"));CharaLibraShortcuts.init({escape:()=>{document.querySelectorAll(".slide-panel").forEach(p=>p.classList.remove("open"));if(!$("detailView").classList.contains("hidden"))$("backBtn").click();},save:saveDetail,theme:()=>$("themeBtn").click()});}
document.addEventListener("DOMContentLoaded",init);
})();
