window.HASHTAG_SEARCHER_I18N = {
  ja: {
    "header.tag.search": "X/Twitter検索",
    "header.tag.daily": "TRPG日常利用",
    "header.tag.local": "ローカル保存",
    "header.title": "使えるハッシュタグ検索",
    "header.description": "TRPGでよく使うX検索をワンクリックで作成できます。ハッシュタグ、検索ワード、フィルター、ネタバレ回避用の除外ワードを組み合わせて、目的に合った検索をすばやく開けます。",
    "mode.title": "検索モード",
    "favorites.title": "お気に入り",
    "favorites.help": "お気に入りはこのブラウザ内にのみ保存され、別端末には引き継がれません。",
    "composer.title": "検索クエリ作成",
    "composer.subtitle": "チップを押して、X検索用のクエリを組み立てます。",
    "composer.spoiler": "ネタバレ回避 ON",
    "composer.baseLabel": "基本タグ / キーワード",
    "composer.addWords": "追加ワード",
    "composer.filters": "フィルター",
    "composer.excludes": "除外ワード",
    "composer.generated": "生成された検索文",
    "button.reset": "リセット",
    "button.openX": "X検索を開く →",
    "button.copyQuery": "検索文をコピー",
    "button.saveFavorite": "お気に入りに保存",
    "scenario.title": "シナリオ名検索",
    "scenario.subtitle": "シナリオ名から関連検索をまとめて作成します。",
    "daily.title": "今日の巡回",
    "daily.subtitle": "日常的に見るTRPG検索へワンクリックで移動します。",
    "preset.title": "プリセット検索カード",
    "preset.subtitle": "TRPGの日常利用に向けた、すぐ使える検索セットです。",
    "preset.copyMarkdown": "選択項目をMarkdownでコピー"
  },
  en: {
    "header.tag.search": "X/Twitter Search",
    "header.tag.daily": "TRPG Daily Use",
    "header.tag.local": "Local Save",
    "header.title": "Useful Hashtag Search",
    "header.description": "Build useful TRPG X searches with one click. Combine hashtags, search words, filters, and spoiler-safe excludes.",
    "mode.title": "Search Modes",
    "favorites.title": "Favorites",
    "favorites.help": "Favorites are saved only in this browser and will not transfer to another device.",
    "composer.title": "Search Query Composer",
    "composer.subtitle": "Press chips to construct your X search query.",
    "composer.spoiler": "Spoiler Safe ON",
    "composer.baseLabel": "Base Tags / Keywords",
    "composer.addWords": "Add Words",
    "composer.filters": "Filters",
    "composer.excludes": "Exclude Words",
    "composer.generated": "Generated Query",
    "button.reset": "Reset",
    "button.openX": "Open X Search →",
    "button.copyQuery": "Copy Query",
    "button.saveFavorite": "Save Favorite",
    "scenario.title": "Scenario Name Search",
    "scenario.subtitle": "Generate related searches from a scenario title.",
    "daily.title": "Daily Patrol",
    "daily.subtitle": "One-click routes for daily TRPG browsing.",
    "preset.title": "Preset Search Cards",
    "preset.subtitle": "Ready-to-use searches for daily TRPG browsing.",
    "preset.copyMarkdown": "Copy Selected as Markdown"
  }
};
