window.WEAPONS = [
  {
    id: "foil_sharpened_6e",
    name: "とがらせたフェンシング・フォイル",
    ruleType: "6e",
    ruleLabels: ["6版"],
    group: "近接戦闘武器",
    category: "ソード",
    skill: "ソード",
    hit: "20",
    damage: "1D6+db",
    range: "タッチ",
    attacks: "1",
    ammo: "―",
    durability: "10",
    malfunction: "―",
    source: "",
    sourceShort: "",
    page: "",
    tags: ["近接戦闘武器", "ソード"],
    note: ""
  },
  {
    id: "rapier_heavy_epee_6e",
    name: "レイピア、重いエペ",
    ruleType: "6e",
    ruleLabels: ["6版"],
    group: "近接戦闘武器",
    category: "ソード",
    skill: "ソード",
    hit: "20",
    damage: "1D6+1+db",
    range: "タッチ",
    attacks: "1",
    ammo: "―",
    durability: "15",
    malfunction: "―",
    source: "",
    sourceShort: "",
    page: "",
    tags: ["近接戦闘武器", "ソード"],
    note: ""
  },
  {
    id: "cavalry_saber_6e",
    name: "騎兵用サーベル",
    ruleType: "6e",
    ruleLabels: ["6版"],
    group: "近接戦闘武器",
    category: "ソード",
    skill: "ソード",
    hit: "20",
    damage: "1D8+1+db",
    range: "タッチ",
    attacks: "1",
    ammo: "―",
    durability: "20",
    malfunction: "―",
    source: "",
    sourceShort: "",
    page: "",
    tags: ["近接戦闘武器", "ソード"],
    note: ""
  },
  {
    id: "brass_knuckles_6e",
    name: "ブラス・ナックル",
    ruleType: "6e",
    ruleLabels: ["6版"],
    group: "近接戦闘武器",
    category: "ナイフ",
    skill: "ナイフ",
    hit: "25",
    damage: "1D3+1+db",
    range: "タッチ",
    attacks: "1",
    ammo: "―",
    durability: "―",
    malfunction: "―",
    source: "",
    sourceShort: "",
    page: "",
    tags: ["近接戦闘武器", "ナイフ"],
    note: ""
  },
  {
    id: "small_knife_6e",
    name: "小型ナイフ*（飛び出しナイフなど）",
    ruleType: "6e",
    ruleLabels: ["6版"],
    group: "近接戦闘武器",
    category: "ナイフ",
    skill: "ナイフ",
    hit: "25",
    damage: "1D4+db",
    range: "タッチ",
    attacks: "1",
    ammo: "―",
    durability: "―",
    malfunction: "―",
    source: "",
    sourceShort: "",
    page: "",
    tags: ["近接戦闘武器", "ナイフ"],
    note: ""
  },
  {
    id: "medium_knife_6e",
    name: "中型ナイフ*（肉切り包丁、ファイティング・ナイフなど）",
    ruleType: "6e",
    ruleLabels: ["6版"],
    group: "近接戦闘武器",
    category: "ナイフ",
    skill: "ナイフ",
    hit: "25",
    damage: "1D4+2+db",
    range: "タッチ",
    attacks: "1",
    ammo: "―",
    durability: "15",
    malfunction: "―",
    source: "",
    sourceShort: "",
    page: "",
    tags: ["近接戦闘武器", "ナイフ"],
    note: ""
  },
  {
    id: "large_knife_6e",
    name: "大型ナイフ*（マチェットなど）",
    ruleType: "6e",
    ruleLabels: ["6版"],
    group: "近接戦闘武器",
    category: "ナイフ",
    skill: "ナイフ",
    hit: "25",
    damage: "1D8+db",
    range: "タッチ",
    attacks: "1",
    ammo: "―",
    durability: "20",
    malfunction: "―",
    source: "",
    sourceShort: "",
    page: "",
    tags: ["近接戦闘武器", "ナイフ"],
    note: ""
  }
];
