window.CHARASHI_I18L = {
  ja: {
    pageTitle: "KP用キャラシビューアー",
    brandKicker: "TRPG WEBツール",
    appTitle: "KP用キャラシビューアー",
    appDesc: "いあきゃらのコマ出力データを貼り付けると、KP用のPCカードをすぐ表示します。",
    formatToggle: "チャパレ整形",
    formatToggleTitle: "貼り付けたチャットパレットを整形して表示・コピーします",
    deleteAll: "全データ削除",
    pasteTitle: "いあきゃら コマ出力データを貼り付け",
    pasteNote: "このエリア上で Ctrl / Cmd + V すると、いあきゃらのコマ出力データを読み込んでカードを生成します。カードはこのレイヤーの上に表示されます。",
    deleteTitle: "すべてのPCカードを削除しますか？",
    deleteTextDefault: "現在表示されているPCカードをすべて削除します。この操作は取り消せません。",
    cancel: "キャンセル",
    deleteAllConfirm: "すべて削除",
    manualCopyTitle: "手動コピーが必要です",
    manualCopyText: "この環境ではClipboard APIがブロックされています。下のテキストを選択済みなので、Ctrl / Cmd + Cでコピーしてください。",
    close: "閉じる",
    skills: "技能",
    noSkills: "技能なし",
    chatPalette: "チャットパレット",
    formattedPalette: "整形済みチャットパレット",
    copyPalette: "チャパレコピー",
    copyKoma: "コマ出力データコピー",
    delete: "削除",
    copied: "コピー済み",
    manualCopy: "手動コピー",
    cardDeleted: "PCカードをすべて削除しました。",
    parseError: "いあきゃらのコマ出力データとして読み込めませんでした。",
    saveError: "保存に失敗しました。ブラウザのlocalStorage制限を確認してください。",
    clipboardBlocked: "Clipboard APIがブロックされたため、手動コピー用のダイアログを開きました。",
    unnamed: "名称未設定",
    noImage: "画像なし",
    dragToReorder: "ドラッグして並び替え"
  },
  en: {
    pageTitle: "Keeper Character Sheet Viewer",
    brandKicker: "TRPG Web Tools",
    appTitle: "Keeper Character Sheet Viewer",
    appDesc: "Paste Iachara koma export data to instantly create PC cards for Keeper reference.",
    formatToggle: "Format Palette",
    formatToggleTitle: "Format imported chat palette before display and copy.",
    deleteAll: "Delete All Data",
    pasteTitle: "Paste Iachara Koma Export Data",
    pasteNote: "Hover this area and press Ctrl / Cmd + V to import Iachara koma export data. Cards appear above this layer.",
    deleteTitle: "Delete all PC cards?",
    deleteTextDefault: "This will delete all currently displayed PC cards. This action cannot be undone.",
    cancel: "Cancel",
    deleteAllConfirm: "Delete All",
    manualCopyTitle: "Manual Copy Required",
    manualCopyText: "Clipboard API is blocked in this environment. The text below is selected, so press Ctrl / Cmd + C to copy it.",
    close: "Close",
    skills: "Skills",
    noSkills: "No skills",
    chatPalette: "Chat Palette",
    formattedPalette: "Formatted Chat Palette",
    copyPalette: "Copy Palette",
    copyKoma: "Copy Koma Data",
    delete: "Delete",
    copied: "Copied",
    manualCopy: "Manual Copy",
    cardDeleted: "All PC cards were deleted.",
    parseError: "Could not read this as Iachara koma export data.",
    saveError: "Save failed. Please check your browser localStorage limits.",
    clipboardBlocked: "Clipboard API was blocked. Manual copy dialog opened.",
    unnamed: "Unnamed",
    noImage: "No Image",
    dragToReorder: "Drag to reorder"
  }
};
