/* NPCデータリーダー i18l.js
   v1.47: JP/EN translation dictionary. */
window.NPC_DATA_READER_I18L = {
  ja: {
    appTitle: 'NPCデータリーダー',
    appSubtitle: 'シナリオNPC情報 → チャットパレット / CCFOLIA用NPC駒JSON',
    usage: '使い方',
    shortcuts: 'ショートカット',
    theme: 'Light / Night',
    close: '×',
    shortcutSub: 'Esc またはショートカットボタンで閉じます。',
    usageSub: 'Esc または使い方ボタンで閉じます。',
    scEsc: 'パネル展開時：パネルを閉じる / パネル非展開時：入力データをリセット（確認あり）',
    scPaste: 'クリップボードにあるNPC情報を貼り付け',
    scTheme: 'ナイト / ライトモード切替',
    scCopyJson: '生成済みJSON駒データをコピー',
    usageBasicTitle: '基本の流れ',
    usageBasic1: '左欄に、シナリオ本文やPDFからコピーしたNPCデータを貼り付けます。',
    usageBasic2Prefix: '解析する',
    usageBasic2: 'を押すと、中央欄にNPC名・ステータス・戦闘・技能が整理されます。',
    usageBasic3: '中央欄の内容を編集すると、右欄のチャットパレットとNPC駒JSONへ自動反映されます。',
    usageBasic4: 'チャットパレット欄は直接編集できます。編集内容はJSONの',
    usageBasic4Suffix: 'に反映されます。',
    usageBasic5Prefix: 'コピー',
    usageBasic5Middle: 'または',
    usageBasic5Json: 'NPC駒データコピー',
    usageBasic5Suffix: 'で、CCFOLIA等へ貼り付けます。',
    usageSafetyTitle: '安全仕様',
    usageSafety1: 'CCFOLIA駒の',
    usageSafety1Suffix: 'は、秘匿情報の漏洩を防ぐため、初期値をNPC名のみにしています。',
    usageSafety2: '装甲や技能など、内容が空のカテゴリはチャットパレットに出力されません。',
    usageNotationTitle: '対応している表記',
    usageNotation1: '近接戦闘（格闘）60%（30/12）、ダメージ 1D3+DB のような公式シナリオ風の表記に対応します。括弧内のハード/イクストリーム値は自動で除外します。',
    leftTitle: '1. NPC情報を貼り付け',
    pdfTxt: 'PDF / TXT対応',
    rawPlaceholder: 'シナリオPDF・txt・メモからコピーしたNPCデータを貼り付けてください。',
    parse: '解析する',
    sample: 'サンプル入力',
    clear: '入力をクリア',
    leftHint: 'PDF由来の改行崩れ、全角スペース、括弧内のハード/イクストリーム値をある程度吸収します。',
    usageList1: 'シナリオ本文やNPCデータを左欄に貼り付けます。',
    usageList2: '解析後、中央欄で名前・ステータス・技能・メモを確認します。',
    usageList3: '中央欄の編集は右欄のチャットパレットとJSONに反映されます。',
    usageList4: 'チャットパレット欄は直接編集できます。',
    usageList5: 'JSONは直接編集不可。編集済みチャパレはJSONの commands に反映されます。',
    usageList6: 'CCFOLIA駒の memo は秘匿漏れ防止のため、初期値をNPC名のみにします。',
    editTitle: '2. NPCデータ編集',
    npcName: 'NPC名',
    npcTitle: '説明 / 肩書き',
    system: 'システム',
    autoMode: '自動判定',
    coc7: 'CoC 7版',
    coc6: 'CoC 6版',
    generic: '汎用',
    resolved: '実判定',
    status: 'ステータス',
    hp: 'HP / 耐久力',
    mp: 'MP',
    san: 'SAN / 正気度',
    db: 'DB',
    build: 'ビルド',
    move: '移動',
    abilities: '能力値',
    combat: '戦闘',
    combatName: '技能 / 行動名',
    rate: '成功率',
    damageMemo: 'ダメージ / メモ',
    addCombat: '戦闘技能を追加',
    armor: '装甲',
    skills: '技能',
    skillName: '技能名',
    addSkill: '技能を追加',
    charMemo: 'キャラメモ',
    memoHint: '初期値はNPC名のみ。公開駒に秘匿情報を入れないための安全仕様です。',
    paletteTitle: '3. チャットパレット',
    copy: 'コピー',
    paletteNote: 'この欄は直接編集可能。編集内容はJSONの commands に反映されます。',
    jsonTitle: 'CCFOLIA用NPC駒JSON',
    npcJsonCopy: 'NPC駒データコピー',
    jsonNote: 'JSONは直接編集不可。中央欄とチャットパレットから自動生成されます。memo初期値はNPC名のみです。',
    autoDetected: '自動判定: ',
    copiedPalette: 'チャットパレットをコピーしました',
    copiedJson: 'NPC駒データをコピーしました',
    languageChanged: '表示言語を切り替えました',
    noClipboardText: 'クリップボードに貼り付け可能なテキストがありません',
    clipboardPasted: 'クリップボードのNPC情報を貼り付けました',
    clipboardError: 'クリップボードを読み取れませんでした',
    resetConfirm: '入力データをリセットします。よろしいですか？',
    resetDone: '入力データをリセットしました',
    footerTitle: '利用上の注意',
    footerNotice1Prefix: '本ツールは、開発者',
    footerNotice1Suffix: 'による個人制作の非公式TRPG支援ツールです。各TRPGシステム、シナリオ、外部サービスの利用規約・権利表記については、利用者自身でご確認ください。',
    footerNotice2Prefix: '不具合報告や要望は、Xの',
    footerNotice2Suffix: '宛のDMにてお送りください。ただし、すべての報告や要望に返信・対応できるとは限りません。',
    xShareTitle: 'Xで共有',
    closeShortcutLabel: 'ショートカットを閉じる',
    closeUsageLabel: '使い方を閉じる'
  },
  en: {
    appTitle: 'NPC Data Reader',
    appSubtitle: 'Scenario NPC data → Chat palette / CCFOLIA NPC character JSON',
    usage: 'How to Use',
    shortcuts: 'Shortcuts',
    theme: 'Light / Night',
    close: '×',
    shortcutSub: 'Press Esc or the Shortcuts button to close this panel.',
    usageSub: 'Press Esc or the How to Use button to close this panel.',
    scEsc: 'When a panel is open: close the panel / otherwise: reset input data after confirmation',
    scPaste: 'Paste NPC information from the clipboard',
    scTheme: 'Toggle Night / Light mode',
    scCopyJson: 'Copy the generated NPC character JSON',
    usageBasicTitle: 'Basic Workflow',
    usageBasic1: 'Paste NPC data copied from a scenario text, PDF, or notes into the left column.',
    usageBasic2Prefix: 'Parse',
    usageBasic2: 'to organize the NPC name, status, combat actions, and skills in the middle column.',
    usageBasic3: 'Edits in the middle column are automatically reflected in the chat palette and NPC character JSON on the right.',
    usageBasic4: 'The chat palette box is directly editable. Its contents are reflected in the JSON',
    usageBasic4Suffix: 'field.',
    usageBasic5Prefix: 'Copy',
    usageBasic5Middle: 'or',
    usageBasic5Json: 'Copy NPC Character Data',
    usageBasic5Suffix: 'to paste the output into CCFOLIA or another tool.',
    usageSafetyTitle: 'Safety Behavior',
    usageSafety1: 'The CCFOLIA character',
    usageSafety1Suffix: 'field defaults to the NPC name only to avoid leaking hidden scenario information.',
    usageSafety2: 'Empty categories such as armor or skills are not included in the chat palette.',
    usageNotationTitle: 'Supported Notation',
    usageNotation1: 'Supports common official-scenario-style notation such as “Melee (Brawl) 60% (30/12), damage 1D3+DB”. Hard/extreme values in parentheses are removed automatically.',
    leftTitle: '1. Paste NPC Information',
    pdfTxt: 'PDF / TXT ready',
    rawPlaceholder: 'Paste NPC data copied from a scenario PDF, txt file, or notes.',
    parse: 'Parse',
    sample: 'Sample Input',
    clear: 'Clear Input',
    leftHint: 'Handles some PDF line-break issues, full-width spaces, and hard/extreme values in parentheses.',
    usageList1: 'Paste scenario text or NPC data into the left column.',
    usageList2: 'After parsing, review the name, status, skills, and memo in the middle column.',
    usageList3: 'Edits in the middle column are reflected in the chat palette and JSON on the right.',
    usageList4: 'The chat palette field can be edited directly.',
    usageList5: 'The JSON is read-only. Edited chat palette text is reflected in the JSON commands field.',
    usageList6: 'The CCFOLIA memo field defaults to the NPC name only to avoid leaking hidden information.',
    editTitle: '2. Edit NPC Data',
    npcName: 'NPC Name',
    npcTitle: 'Description / Role',
    system: 'System',
    autoMode: 'Auto Detect',
    coc7: 'CoC 7th',
    coc6: 'CoC 6th',
    generic: 'Generic',
    resolved: 'Detected System',
    status: 'Status',
    hp: 'HP',
    mp: 'MP',
    san: 'SAN',
    db: 'DB',
    build: 'Build',
    move: 'Move',
    abilities: 'Characteristics',
    combat: 'Combat',
    combatName: 'Skill / Action',
    rate: 'Rate',
    damageMemo: 'Damage / Memo',
    addCombat: 'Add Combat Row',
    armor: 'Armor',
    skills: 'Skills',
    skillName: 'Skill Name',
    addSkill: 'Add Skill',
    charMemo: 'Character Memo',
    memoHint: 'Defaults to the NPC name only. This prevents hidden information from being placed on a public character token.',
    paletteTitle: '3. Chat Palette',
    copy: 'Copy',
    paletteNote: 'This field is editable. Its contents are reflected in the JSON commands field.',
    jsonTitle: 'CCFOLIA NPC Character JSON',
    npcJsonCopy: 'Copy NPC Character Data',
    jsonNote: 'The JSON is read-only. It is generated from the middle column and the chat palette. The memo field defaults to the NPC name only.',
    autoDetected: 'Auto Detect: ',
    copiedPalette: 'Chat palette copied',
    copiedJson: 'NPC character data copied',
    languageChanged: 'Language switched',
    noClipboardText: 'There is no pasteable text in the clipboard',
    clipboardPasted: 'NPC information pasted from the clipboard',
    clipboardError: 'Could not read the clipboard',
    resetConfirm: 'Reset the input data?',
    resetDone: 'Input data reset',
    footerTitle: 'Usage Notes',
    footerNotice1Prefix: 'This is an unofficial TRPG support tool personally developed by',
    footerNotice1Suffix: 'Please check the terms of use and rights notices for each TRPG system, scenario, and external service yourself.',
    footerNotice2Prefix: 'For bug reports or requests, please send a DM on X to',
    footerNotice2Suffix: 'Please note that not all reports or requests can be answered or addressed.',
    xShareTitle: 'Share on X',
    closeShortcutLabel: 'Close shortcuts',
    closeUsageLabel: 'Close how-to panel'
  }
};
