window.SCENARIO_PDF_PARSER_I18L = {
  ja: {
    "chip.portal": "←TRPG WEBツール観測所",
    "chip.builder": "シナリオ情報カードツールと連携",
    "chip.parser": "PDF整形",
    "tooltip.portal": "TRPG WEBツール観測所に戻る",
    "app.title": "シナリオPDF整形機",
    "app.description": "TRPGシナリオPDFの段組み・不要改行・見出し崩れを整え、コピーしやすいTXTへ変換します。",
    "button.format": "整形実行",
    "button.copyOutput": "出力をコピー",
    "button.usage": "使い方",
    "button.shortcuts": "ショートカット",
    "button.nightMode": "ナイトモード",
    "button.lightMode": "ライトモード",
    "button.sendSnippet": "Snippet Toolへ送る",
    "button.copyShort": "コピー",
    "button.downloadTxt": ".txt",
    "button.replaceCurrent": "置換",
    "button.replaceAll": "すべて置換",
    "button.resetReplace": "置換リセット",
    "section.pdfInput": "PDF入力",
    "section.presets": "整形プリセット",
    "section.options": "整形オプション",
    "section.searchReplace": "検索・置換",
    "section.output": "整形済み出力",
    "label.filename": "ファイル名",
    "section.flow": "想定フロー",
    "pdf.dropMain": "PDFをドラッグ＆ドロップ、またはクリックして選択",
    "pdf.sampleStatus": "現在のサンプル：著作権フリー生成サンプル",
    "pdf.dropSub": "pdf.jsの位置情報を使って行を復元し、ブラウザ上でテキスト抽出します。",
    "placeholder.search": "検索ワード",
    "placeholder.replace": "置換後テキスト",
    "stat.chars": "文字数",
    "stat.lines": "行数",
    "stat.blocks": "ブロック",
    "stat.preset": "プリセット",
    "flow.1.title": "1. PDF入力",
    "flow.1.body": "PDFファイルを開き、テキストを自動抽出する。",
    "flow.2.title": "2. 整形・編集",
    "flow.2.body": "改行・見出し・資料情報を整え、検索・置換で微調整する。",
    "flow.3.title": "3. TXT出力",
    "flow.3.body": "整形済みテキストをコピー、または.txtとして保存する。",
    "flow.4.title": "4. Snippet Toolへ送る",
    "flow.4.body": "編集済みTXTをScenario Info Snippet Toolへ渡し、カード化・タグ付けを続行する。",
    "preset.balanced.label": "標準整形",
    "preset.balanced.desc": "改行・空白・見出しを自然に整理",
    "preset.ccfolia.label": "CCFOLIA向け",
    "preset.ccfolia.desc": "コピペしやすい短めブロックに分割",
    "preset.scenario.label": "シナリオ読込向け",
    "preset.scenario.desc": "情報カード化しやすい構造へ整形",
    "preset.minimal.label": "最小整形",
    "preset.minimal.desc": "余計な空白とページ番号だけ除去",
    "option.removePageNumbers": "ページ番号を削除",
    "option.joinBrokenLines": "途中改行を結合",
    "option.keepDialogueBreaks": "セリフ改行を保持",
    "option.normalizeSpaces": "文字種/スペース正規化",
    "option.removeHeaders": "ヘッダー/フッター候補を削除",
    "option.splitSections": "章・見出しごとに分割",
    "option.markSkillChecks": "技能判定を検出",
    "option.markHandouts": "資料/HO候補を検出",
    "option.fixMergedHeadings": "結合した見出しを分離",
    "option.keepScenarioMetaLines": "TRPG概要項目を保持",
    "option.preservePdfParagraphBreaks": "PDF上の大きな段落間隔を保持",
    "option.removeDuplicateLines": "近接重複行を削除",
    "option.replaceRoleTokens": "KPC/PC/HOを{KPC}/{PC}/{HO}化",
    "toast.copySuccess": "整形済みテキストをコピーしました。",
    "toast.copyFail": "コピーに失敗しました。ブラウザの権限を確認してください。",
    "toast.pdfOnly": "PDFファイルを選択してください。",
    "toast.pdfSuccess": "PDFテキストを抽出して整形しました。",
    "toast.pdfFail": "PDFの読み込みに失敗しました。コピー可能なPDFか確認してください。",
    "toast.bridge": "Snippet Toolへ渡すテキストを保存しました。ページを移動します。",
    "output.empty": "整形結果がここに表示されます。",
    "file.loading": "読み込み中：",
    "file.loaded": "読み込み完了：",
    "file.failed": "読み込み失敗：",
    "pdf.noFileStatus": "PDF未選択：ファイルを開いてください",
    "confirm.resetAll": "開いているPDFと出力テキストを消去します。よろしいですか？",
    "usage.title": "使い方",
    "usage.body": "PDFを読み込むと本文を抽出し、プリセットと整形オプションで不要改行・見出し・資料情報を整理します。検索・置換で微調整したあと、コピー、.txt保存、またはシナリオ情報カードツールへ送ることができます。",
    "shortcuts.title": "ショートカット",
    "shortcuts.body": "Ctrl/⌘+O：PDFを開く ／ Ctrl/⌘+Shift+F：検索欄へ移動 ／ Ctrl/⌘+Shift+T：モード切替 ／ Ctrl/⌘+Shift+C：出力コピー ／ Ctrl/⌘+Shift+S：TXT保存 ／ Esc：パネルを閉じる／通常時はリセット"
  },
  en: {
    "chip.portal": "←TRPG WEB Tools Portal",
    "chip.builder": "Scenario Info Card Tool Bridge",
    "chip.parser": "PDF Formatter",
    "tooltip.portal": "Back to TRPG WEB Tools portal",
    "app.title": "Scenario PDF Formatter",
    "app.description": "Clean TRPG scenario PDF columns, broken line breaks, and merged headings into copy-ready TXT.",
    "button.format": "Format",
    "button.copyOutput": "Copy Output",
    "button.usage": "Guide",
    "button.shortcuts": "Shortcuts",
    "button.nightMode": "Night Mode",
    "button.lightMode": "Light Mode",
    "button.sendSnippet": "Send to Snippet Tool",
    "button.copyShort": "Copy",
    "button.downloadTxt": ".txt",
    "button.replaceCurrent": "Replace",
    "button.replaceAll": "Replace All",
    "button.resetReplace": "Reset Replace",
    "section.pdfInput": "PDF Input",
    "section.presets": "Format Presets",
    "section.options": "Format Options",
    "section.searchReplace": "Search / Replace",
    "section.output": "Formatted Output",
    "label.filename": "File name",
    "section.flow": "Expected Flow",
    "pdf.dropMain": "Drag and drop a PDF, or click to select",
    "pdf.sampleStatus": "Current sample: copyright-free generated sample",
    "pdf.dropSub": "Uses pdf.js position data to restore lines in the browser.",
    "placeholder.search": "Search keyword",
    "placeholder.replace": "Replacement text",
    "stat.chars": "Characters",
    "stat.lines": "Lines",
    "stat.blocks": "Blocks",
    "stat.preset": "Preset",
    "flow.1.title": "1. PDF Input",
    "flow.1.body": "Open a PDF and extract text automatically.",
    "flow.2.title": "2. Format / Edit",
    "flow.2.body": "Clean line breaks, headings, handout markers, and fine tune with search/replace.",
    "flow.3.title": "3. TXT Export",
    "flow.3.body": "Copy the formatted text or save it as a .txt backup.",
    "flow.4.title": "4. Send to Snippet Tool",
    "flow.4.body": "Pass edited TXT to the Scenario Info Snippet Tool for cards, tags, and organization.",
    "preset.balanced.label": "Balanced",
    "preset.balanced.desc": "Clean line breaks, spacing, and headings naturally",
    "preset.ccfolia.label": "For CCFOLIA",
    "preset.ccfolia.desc": "Split into short blocks for easy copy/paste",
    "preset.scenario.label": "For Scenario Import",
    "preset.scenario.desc": "Format for card creation and information tagging",
    "preset.minimal.label": "Minimal",
    "preset.minimal.desc": "Remove extra spacing and page numbers only",
    "option.removePageNumbers": "Remove page numbers",
    "option.joinBrokenLines": "Join broken lines",
    "option.keepDialogueBreaks": "Keep dialogue line breaks",
    "option.normalizeSpaces": "Normalize characters and spacing",
    "option.removeHeaders": "Remove header/footer candidates",
    "option.splitSections": "Split by chapters/headings",
    "option.markSkillChecks": "Detect skill checks",
    "option.markHandouts": "Detect handout/info candidates",
    "option.fixMergedHeadings": "Separate merged headings",
    "option.keepScenarioMetaLines": "Keep TRPG metadata lines",
    "option.preservePdfParagraphBreaks": "Preserve large PDF paragraph gaps",
    "option.removeDuplicateLines": "Remove near duplicate lines",
    "option.replaceRoleTokens": "Replace KPC/PC/HO with {KPC}/{PC}/{HO}",
    "toast.copySuccess": "Copied formatted text.",
    "toast.copyFail": "Copy failed. Check browser clipboard permissions.",
    "toast.pdfOnly": "Please select a PDF file.",
    "toast.pdfSuccess": "Extracted and formatted PDF text.",
    "toast.pdfFail": "Failed to read PDF. Please check if the PDF text is selectable.",
    "toast.bridge": "Saved text for the Snippet Tool. Moving to the next page.",
    "output.empty": "Formatted output will appear here.",
    "file.loading": "Loading: ",
    "file.loaded": "Loaded: ",
    "file.failed": "Failed: ",
    "pdf.noFileStatus": "No PDF selected: open a file",
    "confirm.resetAll": "Clear the opened PDF and output text?",
    "usage.title": "Guide",
    "usage.body": "Open a PDF to extract text, then use presets and formatting options to clean broken line breaks, headings, and handout markers. After search/replace edits, copy, save as .txt, or send the text to the Scenario Info Card Tool.",
    "shortcuts.title": "Shortcuts",
    "shortcuts.body": "Ctrl/⌘+O: Open PDF / Ctrl/⌘+Shift+F: Focus search / Ctrl/⌘+Shift+T: Toggle theme / Ctrl/⌘+Shift+C: Copy output / Ctrl/⌘+Shift+S: Save TXT / Esc: Close panel or reset"
  }
};
