window.SCENARIO_PDF_PARSER_I18L = {
  ja: {
    "chip.portal": "←TRPG WEBツール観測所",
    "chip.builder": "シナリオ情報カードツールと連携",
    "chip.parser": "PDF整形",
    "tooltip.portal": "TRPG WEBツール観測所に戻る",
    "app.title": "シナリオPDF整形機",
    "app.description": "TRPGシナリオPDFの段組み・不要改行・見出し崩れを整え、コピーしやすいTXTへ変換します。",
    "button.format": "整形実行",
    "button.copyOutput": "出力をコピー",
    "button.usage": "使い方",
    "button.shortcuts": "ショートカット",
    "button.nightMode": "ナイトモード",
    "button.lightMode": "ライトモード",
    "button.sendSnippet": "Snippet Toolへ送る",
    "button.copyShort": "コピー",
    "button.downloadTxt": ".txt",
    "button.replaceCurrent": "置換",
    "button.replaceAll": "すべて置換",
    "button.resetReplace": "置換リセット",
    "section.pdfInput": "PDF入力",
    "section.apiConfig": "高精度API設定",
    "api.useExternal": "外部APIを使用する",
    "api.endpointLabel": "API URL",
    "button.testApi": "接続テスト",
    "api.statusNotTested": "未接続",
    "api.statusTesting": "接続確認中...",
    "api.statusOk": "接続OK",
    "api.statusError": "接続できません。ブラウザ抽出へフォールバックします。",
    "api.statusEmpty": "API URLを入力してください。",
    "api.statusDisabled": "外部APIは無効です。",
    "api.noticeTitle": "高精度API利用時の注意",
    "api.noticeBody": "このモードではPDFをAPIへ一時送信して解析します。API側では保存せず、処理後に一時ファイルを削除する設計です。著作物・秘匿情報を含むPDFの扱いにはご注意ください。",
    "section.extractMode": "抽出モード",
    "section.presets": "整形プリセット",
    "section.options": "整形オプション",
    "section.searchReplace": "検索・置換",
    "section.output": "整形済み出力",
    "label.filename": "ファイル名",
    "section.debug": "抽出行デバッグ",
    "debug.note": "読み順・座標・カラム判定を確認できます。",
    "debug.empty": "PDFを読み込むと抽出行デバッグがここに表示されます。",
    "debug.apiUnavailable": "PyMuPDF4LLM APIに接続できませんでした。ブラウザ抽出を使用しています。",
    "section.flow": "想定フロー",
    "pdf.dropMain": "PDFをドラッグ＆ドロップ、またはクリックして選択",
    "pdf.sampleStatus": "現在のサンプル：著作権フリー生成サンプル",
    "pdf.dropSub": "標準ではPyMuPDF4LLM APIで高精度抽出し、失敗時はブラウザ抽出にフォールバックします。",
    "placeholder.search": "検索ワード",
    "placeholder.replace": "置換後テキスト",
    "stat.chars": "文字数",
    "stat.lines": "行数",
    "stat.blocks": "ブロック",
    "stat.preset": "プリセット",
    "flow.1.title": "1. PDF入力",
    "flow.1.body": "PDFファイルを開き、テキストを自動抽出する。",
    "flow.2.title": "2. 整形・編集",
    "flow.2.body": "改行・見出し・資料情報を整え、検索・置換で微調整する。",
    "flow.3.title": "3. TXT出力",
    "flow.3.body": "整形済みテキストをコピー、または.txtとして保存する。",
    "flow.4.title": "4. Snippet Toolへ送る",
    "flow.4.body": "編集済みTXTをScenario Info Snippet Toolへ渡し、カード化・タグ付けを続行する。",
    "preset.balanced.label": "標準整形",
    "preset.balanced.desc": "改行・空白・見出しを自然に整理",
    "preset.ccfolia.label": "CCFOLIA向け",
    "preset.ccfolia.desc": "コピペしやすい短めブロックに分割",
    "preset.scenario.label": "シナリオ読込向け",
    "preset.scenario.desc": "情報カード化しやすい構造へ整形",
    "preset.minimal.label": "最小整形",
    "preset.minimal.desc": "余計な空白とページ番号だけ除去",
    "extract.pymupdf.label": "高精度：Layout解析",
    "extract.pymupdf.desc": "Python APIで座標・罫線・余白・カラム境界を解析する標準モード",
    "extract.raw.label": "PDFテキスト順序優先",
    "extract.raw.desc": "PDF内蔵テキストの読順を優先。まずはこれを推奨",
    "extract.single.label": "座標解析：単一カラム",
    "extract.single.desc": "Y座標で行を復元。単一段組み向け",
    "extract.twoColumn.label": "座標解析：2カラム",
    "extract.twoColumn.desc": "左カラム→右カラムの順で読む。段組み向け",
    "option.removePageNumbers": "ページ番号を削除",
    "option.joinBrokenLines": "途中改行を結合",
    "option.keepDialogueBreaks": "セリフ改行を保持",
    "option.normalizeSpaces": "文字種/スペース正規化",
    "option.removeHeaders": "ヘッダー/フッター候補を削除",
    "option.splitSections": "章・見出しごとに分割",
    "option.markSkillChecks": "技能判定を検出",
    "option.markHandouts": "資料/HO候補を検出",
    "option.fixMergedHeadings": "結合した見出しを分離",
    "option.keepScenarioMetaLines": "TRPG概要項目を保持",
    "option.preservePdfParagraphBreaks": "PDF上の大きな段落間隔を保持",
    "option.removeDuplicateLines": "近接重複行を削除",
    "option.replaceRoleTokens": "KPC/PC/HOを{KPC}/{PC}/{HO}化",
    "toast.copySuccess": "整形済みテキストをコピーしました。",
    "toast.copyFail": "コピーに失敗しました。ブラウザの権限を確認してください。",
    "toast.pdfOnly": "PDFファイルを選択してください。",
    "toast.pdfSuccess": "PDFテキストを抽出して整形しました。",
    "toast.pdfSuccessHighQuality": "Layout解析でPDFテキストを抽出して整形しました。",
    "toast.apiFallback": "PyMuPDF4LLM APIに接続できないため、ブラウザ抽出に切り替えました。",
    "toast.pdfFail": "PDFの読み込みに失敗しました。コピー可能なPDFか確認してください。",
    "toast.bridge": "Snippet Toolへ渡すテキストを保存しました。ページを移動します。",
    "output.empty": "整形結果がここに表示されます。",
    "file.loading": "読み込み中：",
    "file.loaded": "読み込み完了：",
    "file.failed": "読み込み失敗：",
    "pdf.noFileStatus": "PDF未選択：ファイルを開いてください",
    "confirm.resetAll": "開いているPDFと出力テキストを消去します。よろしいですか？",
    "usage.title": "使い方",
    "usage.body": "PDFを読み込むと複数の抽出モードで本文を取得します。標準では高精度：Layout解析を使い、崩れる場合は座標解析モードへ切り替えてください。抽出行デバッグで読順・座標・カラム判定を確認しながら、プリセットと検索・置換で微調整できます。",
    "shortcuts.title": "ショートカット",
    "shortcuts.body": "Ctrl/⌘+O：PDFを開く ／ Ctrl/⌘+Shift+F：検索欄へ移動 ／ Ctrl/⌘+Shift+T：モード切替 ／ Ctrl/⌘+Shift+C：出力コピー ／ Ctrl/⌘+Shift+S：TXT保存 ／ Esc：パネルを閉じる／通常時はリセット"
  },
  en: {
    "chip.portal": "←TRPG WEB Tools Portal",
    "chip.builder": "Scenario Info Card Tool Bridge",
    "chip.parser": "PDF Formatter",
    "tooltip.portal": "Back to TRPG WEB Tools portal",
    "app.title": "Scenario PDF Formatter",
    "app.description": "Clean TRPG scenario PDF columns, broken line breaks, and merged headings into copy-ready TXT.",
    "button.format": "Format",
    "button.copyOutput": "Copy Output",
    "button.usage": "Guide",
    "button.shortcuts": "Shortcuts",
    "button.nightMode": "Night Mode",
    "button.lightMode": "Light Mode",
    "button.sendSnippet": "Send to Snippet Tool",
    "button.copyShort": "Copy",
    "button.downloadTxt": ".txt",
    "button.replaceCurrent": "Replace",
    "button.replaceAll": "Replace All",
    "button.resetReplace": "Reset Replace",
    "section.pdfInput": "PDF Input",
    "section.apiConfig": "High Accuracy API",
    "api.useExternal": "Use external API",
    "api.endpointLabel": "API URL",
    "button.testApi": "Test",
    "api.statusNotTested": "Not connected",
    "api.statusTesting": "Testing...",
    "api.statusOk": "Connection OK",
    "api.statusError": "Could not connect. Falling back to browser extraction.",
    "api.statusEmpty": "Please enter an API URL.",
    "api.statusDisabled": "External API is disabled.",
    "api.noticeTitle": "High accuracy API notice",
    "api.noticeBody": "This mode temporarily sends the PDF to an API for analysis. The API is designed not to store PDFs and to delete temporary files after processing. Be careful when handling copyrighted or hidden scenario content.",
    "section.extractMode": "Extraction Mode",
    "section.presets": "Format Presets",
    "section.options": "Format Options",
    "section.searchReplace": "Search / Replace",
    "section.output": "Formatted Output",
    "label.filename": "File name",
    "section.debug": "Extraction Debug",
    "debug.note": "Check reading order, coordinates, and column detection.",
    "debug.empty": "Debug rows will appear here after loading a PDF.",
    "section.flow": "Expected Flow",
    "pdf.dropMain": "Drag and drop a PDF, or click to select",
    "pdf.sampleStatus": "Current sample: copyright-free generated sample",
    "pdf.dropSub": "Uses the PyMuPDF4LLM API by default, with browser extraction as fallback.",
    "placeholder.search": "Search keyword",
    "placeholder.replace": "Replacement text",
    "stat.chars": "Characters",
    "stat.lines": "Lines",
    "stat.blocks": "Blocks",
    "stat.preset": "Preset",
    "flow.1.title": "1. PDF Input",
    "flow.1.body": "Open a PDF and extract text automatically.",
    "flow.2.title": "2. Format / Edit",
    "flow.2.body": "Clean line breaks, headings, handout markers, and fine tune with search/replace.",
    "flow.3.title": "3. TXT Export",
    "flow.3.body": "Copy the formatted text or save it as a .txt backup.",
    "flow.4.title": "4. Send to Snippet Tool",
    "flow.4.body": "Pass edited TXT to the Scenario Info Snippet Tool for cards, tags, and organization.",
    "preset.balanced.label": "Balanced",
    "preset.balanced.desc": "Clean line breaks, spacing, and headings naturally",
    "preset.ccfolia.label": "For CCFOLIA",
    "preset.ccfolia.desc": "Split into short blocks for easy copy/paste",
    "preset.scenario.label": "For Scenario Import",
    "preset.scenario.desc": "Format for card creation and information tagging",
    "preset.minimal.label": "Minimal",
    "preset.minimal.desc": "Remove extra spacing and page numbers only",
    "extract.raw.label": "Prefer PDF Text Order",
    "extract.raw.desc": "Prefer embedded PDF text order. Recommended first",
    "extract.single.label": "Coordinate: Single Column",
    "extract.single.desc": "Restore lines by Y coordinates for single-column pages",
    "extract.twoColumn.label": "Coordinate: Two Columns",
    "extract.twoColumn.desc": "Read left column then right column for column layouts",
    "option.removePageNumbers": "Remove page numbers",
    "option.joinBrokenLines": "Join broken lines",
    "option.keepDialogueBreaks": "Keep dialogue line breaks",
    "option.normalizeSpaces": "Normalize characters and spacing",
    "option.removeHeaders": "Remove header/footer candidates",
    "option.splitSections": "Split by chapters/headings",
    "option.markSkillChecks": "Detect skill checks",
    "option.markHandouts": "Detect handout/info candidates",
    "option.fixMergedHeadings": "Separate merged headings",
    "option.keepScenarioMetaLines": "Keep TRPG metadata lines",
    "option.preservePdfParagraphBreaks": "Preserve large PDF paragraph gaps",
    "option.removeDuplicateLines": "Remove near duplicate lines",
    "option.replaceRoleTokens": "Replace KPC/PC/HO with {KPC}/{PC}/{HO}",
    "toast.copySuccess": "Copied formatted text.",
    "toast.copyFail": "Copy failed. Check browser clipboard permissions.",
    "toast.pdfOnly": "Please select a PDF file.",
    "toast.pdfSuccess": "Extracted and formatted PDF text.",
    "toast.pdfSuccessHighQuality": "Extracted and formatted PDF text with layout analysis.",
    "toast.apiFallback": "Could not connect to the PyMuPDF4LLM API. Switched to browser extraction.",
    "toast.pdfFail": "Failed to read PDF. Please check if the PDF text is selectable.",
    "toast.bridge": "Saved text for the Snippet Tool. Moving to the next page.",
    "output.empty": "Formatted output will appear here.",
    "file.loading": "Loading: ",
    "file.loaded": "Loaded: ",
    "file.failed": "Failed: ",
    "pdf.noFileStatus": "No PDF selected: open a file",
    "confirm.resetAll": "Clear the opened PDF and output text?",
    "usage.title": "Guide",
    "usage.body": "Open a PDF to extract text in multiple modes. Start with Prefer PDF Text Order, then switch to coordinate modes if the reading order breaks. Use Extraction Debug to inspect reading order, coordinates, and column detection, then fine tune with presets and search/replace.",
    "shortcuts.title": "Shortcuts",
    "shortcuts.body": "Ctrl/⌘+O: Open PDF / Ctrl/⌘+Shift+F: Focus search / Ctrl/⌘+Shift+T: Toggle theme / Ctrl/⌘+Shift+C: Copy output / Ctrl/⌘+Shift+S: Save TXT / Esc: Close panel or reset"
  }
};
