let lastRawGeneratedText='',rawManualDecorations='',isResetting=false;
const $=id=>document.getElementById(id);
const asciiGroups={
  LINE:[['✦ line','✦   ┈┈┈┈┈┈┈┈┈┈┈┈   ✦'],['⟡ line','⟡.· ⎯⎯⎯⎯⎯⎯⎯⎯ ⟡.·'],['✤ line','✤─────✤─────✤'],['○● line','○●————————————————-●○'],['plain line','──────────────────'],['─ ⋅ ✩ ⋅ ─ line','──────── ⋅ ✩ ⋅ ────────'],['꒰ঌ line ໒꒱','꒰ঌ ┈┈┈┈┈┈┈┈ ໒꒱'],['⋆⸜ line ⸝⋆','⋆⸜ ┈┈┈┈┈┈┈┈ ⸝⋆'],['◇ line','◇─◇──◇────◇──◇─◇'],['◆◇ line','◆◇◆◇◆◇◆◇◆◇◆◇◆'],['◈ line','◈ ━━━━━━━━━━━━━━ ◈'],['▣ line','▣──────────────▣'],['╋ line','╋━━━━━━━━━━━━━━╋']],
  'SINGLE CHARACTER':[['❏','❏'],['✦','✦'],['✧','✧'],['┗','┗ '],['┊','┊'],['▎','▎'],['◤','◤'],['◢','◢']],
  ARTS:[['.+:ﾟ+｡.☆','.+:ﾟ+｡.☆'],['｡:+* ﾟ','｡:+* ﾟ ゜ﾟ *+:｡:+* ﾟ ゜ﾟ *+:｡'],['✧･ﾟ:*','✧･ﾟ: *✧･ﾟ:* 　　 *:･ﾟ✧*:･ﾟ✧'],['✦⋆｡˚','✦⋆｡˚ ⋆｡˚ ✦ ⋆｡˚ ⋆｡˚✦'],['𓂃𓈒𓏸','𓂃𓈒𓏸︎︎︎︎ 🕊'],['✦⋆˙₊⟡','✦⋆˙₊⟡'],['⊹₊⋆ ✦. ݁','⊹₊⋆ ✦. ݁'],['Cᵃˡˡ ᵒᶠ Cᵗʰᵘˡʰᵘ','Cᵃˡˡ ᵒᶠ Cᵗʰᵘˡʰᵘ'],['◤￣￣','◤￣￣￣￣￣￣￣￣￣￣￣￣￣￣'],['＿＿◢','＿＿＿＿＿＿＿＿＿＿＿＿＿＿◢']]
};
function renderAsciiOptions(){const root=$('asciiOptions');root.innerHTML='';Object.entries(asciiGroups).forEach(([title,items])=>{const group=document.createElement('div');group.className='ascii-group';group.innerHTML=`<div class="ascii-group-title">${title}</div><div class="btns"></div>`;const box=group.querySelector('.btns');items.forEach(([label,value])=>{const btn=document.createElement('button');btn.type='button';btn.textContent=label;btn.dataset.decoration=value;btn.addEventListener('click',()=>addDecoration(value));box.appendChild(btn)});root.appendChild(group)})}
function suffixName(name,suffix){const t=String(name).trim();return !t||suffix==='none'||t.endsWith(suffix)?t:`${t}${suffix}`}
function getSelectedSuffix(){return document.querySelector('input[name="suffixChoice"]:checked')?.value||'none'}
function selectSuffix(target){document.querySelectorAll('input[name="suffixChoice"]').forEach(input=>input.checked=input===target);if(!target.checked)target.checked=true;previewSelectedStyle()}
function escapeHtml(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function getSystemText(mode='normal'){const key=$('systemSelect').value;if(key==='custom')return $('customSystemText').value.trim()||'システム名';return ReportParser.systemMaps[mode]?.[key]||ReportParser.systemMaps.normal[key]||key}
function addGM(value='',role='KP'){const row=document.createElement('div');row.className='row';row.innerHTML=`<div><label>役割</label><select class="gm-role"><option value="KP">KP</option><option value="DL">DL</option><option value="GM">GM</option><option value="KPC/KP">KPC/KP</option><option value="SKP">SKP</option><option value="作/KP">作/KP</option><option value="進行">進行</option></select></div><div><label>名前</label><input class="gm-name" value="${escapeHtml(value)}" placeholder="例：KPC名 / KP名"></div><button class="icon-button add-inline" type="button">＋</button><button class="icon-button danger-inline" type="button">×</button>`;$('gmContainer').appendChild(row);row.querySelector('.gm-role').value=role;row.querySelector('.add-inline').addEventListener('click',()=>addGM());row.querySelector('.danger-inline').addEventListener('click',()=>{row.remove();previewSelectedStyle()})}
function getParticipantBaseSlot(){return document.querySelector('#playerContainer .participant-row .player-slot')?.value||'PC1'}
function getParticipantSlotForIndex(i){const base=getParticipantBaseSlot();if(/^PC[0-9]+$/i.test(base))return `PC${i}`;if(/^HO[0-9]+$/i.test(base))return `HO${i}`;return base}
function buildSlotOptions(selected='PC1',isFirst=false){const options=isFirst?['PC','PC1','HO1','PC/PL','PL/PC','自由']:[selected];return options.map(v=>`<option value="${v}" ${v===selected?'selected':''}>${v}</option>`).join('')}
function syncParticipantSlots(){[...document.querySelectorAll('#playerContainer .participant-row')].forEach((row,i)=>{const sel=row.querySelector('.player-slot');if(!sel)return;if(i===0){sel.innerHTML=buildSlotOptions(sel.value||'PC1',true);sel.disabled=false}else{const slot=getParticipantSlotForIndex(i+1);sel.innerHTML=buildSlotOptions(slot);sel.value=slot;sel.disabled=true}})}
function addPlayer(pl='',pc='',slot='',ho=''){const container=$('playerContainer'),idx=container.querySelectorAll('.participant-row').length+1,isFirst=idx===1,selected=slot||getParticipantSlotForIndex(idx),row=document.createElement('div');row.className=`participant-row name-order-${$('nameInputOrder')?.value||'pcpl'}`;row.innerHTML=`<div class="slot-field"><label>枠</label><select class="player-slot" ${isFirst?'':'disabled'}>${buildSlotOptions(selected,isFirst)}</select></div><div class="ho-field"><label>HO補足</label><input class="ho-name" value="${escapeHtml(ho)}" placeholder="通常は空欄でOK"></div><div class="pc-field"><label>PC名</label><input class="pc-name" value="${escapeHtml(pc)}" placeholder="例：探索者名"></div><div class="pl-field"><label>PL名</label><input class="pl-name" value="${escapeHtml(pl)}" placeholder="例：佐藤"></div><button class="danger delete-field" type="button">×</button>`;container.appendChild(row);row.querySelector('.player-slot').addEventListener('change',()=>{syncParticipantSlots();previewSelectedStyle()});row.querySelector('.delete-field').addEventListener('click',()=>{row.remove();syncParticipantSlots();previewSelectedStyle()});syncParticipantSlots();updateNameInputOrder()}
function updateNameInputOrder(){const order=$('nameInputOrder')?.value||'pcpl';document.querySelectorAll('.participant-row').forEach(row=>{row.classList.toggle('name-order-plpc',order==='plpc');row.classList.toggle('name-order-pcpl',order==='pcpl')})}
function samplePlayerName(index,type){const letters=['A','B','C','D','E','F','G','H','I'];const letter=letters[index]||String(index+1);return type==='pc'?`探索者${letter}`:`PL名${letter}`}
function getFieldValue(id,useSample,sampleValue){const value=$(id).value.trim();return value||(useSample?sampleValue:'')}
function collectData(useSample=false){const suffix=getSelectedSuffix();let gms=[...document.querySelectorAll('#gmContainer .row')].map((row,index)=>{const raw=row.querySelector('.gm-name').value.trim();return{role:row.querySelector('.gm-role').value||'KP',name:suffixName(raw||(useSample&&index===0?'KP名':''),suffix)}}).filter(x=>x.name);let players=[...document.querySelectorAll('#playerContainer .participant-row')].map((row,index)=>{const rawPc=row.querySelector('.pc-name').value.trim(),rawPl=row.querySelector('.pl-name').value.trim();return{slot:row.querySelector('.player-slot').value,ho:row.querySelector('.ho-name').value.trim(),pc:rawPc||(useSample?samplePlayerName(index,'pc'):''),pl:suffixName(rawPl||(useSample?samplePlayerName(index,'pl'):''),suffix)}}).filter(x=>x.pl||x.pc||x.ho);if(useSample){if(!gms.length)gms=[{role:'KP',name:'KP名'}];if(!players.length)players=[{slot:'HO1',ho:'',pc:'探索者A',pl:'PL名A'},{slot:'HO2',ho:'',pc:'探索者B',pl:'PL名B'}]}return{style:$('reportStyle').value,fontVariant:$('fontVariant').value,systemShort:getSystemText('short'),systemLower:getSystemText('lower'),systemBold:getSystemText('bold'),scenario:getFieldValue('scenarioTitle',useSample,'シナリオ名'),result:getFieldValue('resultText',useSample,'END A 両生還'),author:getFieldValue('authorText',useSample,'作者名 様'),date:getFieldValue('dateText',useSample,$('dateText').placeholder||getTodayString()),quote:getFieldValue('quoteText',useSample,'「忘れられない卓でした」'),hashtags:$('hashtagText').value.trim(),gms,players}}
function hasUserInput(){return ['scenarioTitle','resultText','authorText','dateText','quoteText','hashtagText'].some(id=>$(id).value.trim())||[...document.querySelectorAll('#gmContainer input,#playerContainer input')].some(i=>i.value.trim())}
function composeRawPreview(){return [lastRawGeneratedText,rawManualDecorations].filter(Boolean).join('\n\n')}
function renderPreview(){const d=collectData(!hasUserInput()),variant=d.style==='minimal'?'plain':d.fontVariant;$('tweetPreview').value=ReportParser.styleTextPreservingSamples(composeRawPreview(),variant);updateCount();requestAnimationFrame(fitPreviewTextBox)}
function generateTweet(options={}){const d=collectData(Boolean(options.useSampleFallback));lastRawGeneratedText=(ReportParser.templates[d.style]||ReportParser.templates.classic)(d);renderPreview()}
function previewSelectedStyle(){if(isResetting)return;if($('reportStyle').value==='ho-focus'){const first=document.querySelector('#playerContainer .participant-row .player-slot');if(first&&first.value!=='HO1'){first.value='HO1';syncParticipantSlots()}}generateTweet({useSampleFallback:true})}
function addDecoration(text){rawManualDecorations=[rawManualDecorations,text].filter(Boolean).join('\n');renderPreview();$('tweetPreview').focus()}
function insertAtCursor(text){const a=$('tweetPreview'),s=a.selectionStart,e=a.selectionEnd;a.value=a.value.slice(0,s)+text+a.value.slice(e);a.focus();a.selectionStart=a.selectionEnd=s+text.length;updateCount()}
function clearPreview(){lastRawGeneratedText='';rawManualDecorations='';$('tweetPreview').value='';updateCount();$('tweetPreview').focus()}
async function copyTweet(){try{await navigator.clipboard.writeText($('tweetPreview').value);alert('コピーしました。')}catch(e){$('tweetPreview').select();document.execCommand('copy');alert('コピーしました。')}}
function getTweetWeightedLength(text){let total=0;for(const ch of Array.from(text.normalize('NFC'))){const cp=ch.codePointAt(0);if(cp===10||cp===13||cp<=0x10FF||(cp>=0x2000&&cp<=0x200D)||(cp>=0x2010&&cp<=0x201F)||(cp>=0x2032&&cp<=0x2037)){total+=1}else total+=2}return total}
function updateCount(){const n=getTweetWeightedLength($('tweetPreview').value),s=$('limitStatus');$('charCount').textContent=`${n} / 280`;s.textContent=n<=280?'OK':`${n-280}字オーバー`;s.className=n<=280?'count-ok':'count-bad'}
function fitPreviewTextBox(){const panel=document.querySelector('.preview-panel'),card=document.querySelector('.twitter-card'),text=$('tweetPreview');if(!panel||!card||!text||window.innerWidth<=980)return;const h2=panel.querySelector('h2'),head=card.querySelector('.tweet-head'),count=card.querySelector('.count-line'),buttons=card.querySelector('.btns');const chrome=32+(h2?.offsetHeight||0)+(head?.offsetHeight||0)+(count?.offsetHeight||0)+(buttons?.offsetHeight||0);const available=panel.clientHeight-chrome;const minH=window.innerHeight<760?150:180;text.style.height=`${Math.max(minH,Math.min(360,available))}px`}
function getTodayString(){const d=new Date();return `${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}`}
function setTodayPlaceholder(){$('dateText').placeholder=getTodayString()}
function updateCustomSystemInput(){const input=$('customSystemText');if(input)input.classList.toggle('is-active',$('systemSelect').value==='custom')}
function resetFormState(){isResetting=true;document.querySelectorAll('.input-panel input:not([type="checkbox"]),.input-panel textarea').forEach(el=>el.value='');$('systemSelect').value='call_of_cthulhu';updateCustomSystemInput();$('reportStyle').value='classic';$('fontVariant').value='sansBoldItalic';$('nameInputOrder').value='pcpl';document.querySelectorAll('input[name="suffixChoice"]').forEach(input=>input.checked=input.value==='none');$('gmContainer').innerHTML='';$('playerContainer').innerHTML='';lastRawGeneratedText='';rawManualDecorations='';$('tweetPreview').value='';updateCount();addGM();addPlayer();addPlayer();setTodayPlaceholder();isResetting=false}
window.clearAll=resetFormState;
function bindEvents(){window.addEventListener('resize',fitPreviewTextBox);document.querySelectorAll('input[name="suffixChoice"]').forEach(input=>input.addEventListener('change',()=>selectSuffix(input)));$('addPlayerButton').addEventListener('click',()=>addPlayer());$('generateButton').addEventListener('click',()=>generateTweet());$('clearAllButton').addEventListener('click',resetFormState);$('copyButton').addEventListener('click',copyTweet);$('newlineButton').addEventListener('click',()=>insertAtCursor('\n'));$('spaceButton').addEventListener('click',()=>insertAtCursor(' '));$('clearPreviewButton').addEventListener('click',clearPreview);$('reportStyle').addEventListener('change',previewSelectedStyle);$('fontVariant').addEventListener('change',renderPreview);$('nameInputOrder').addEventListener('change',()=>{updateNameInputOrder();previewSelectedStyle()});$('tweetPreview').addEventListener('input',updateCount);document.querySelector('.input-panel').addEventListener('input',e=>{if(!isResetting&&e.target.id!=='tweetPreview')previewSelectedStyle()});document.querySelector('.input-panel').addEventListener('change',e=>{if(isResetting)return;if(e.target.id==='systemSelect'){updateCustomSystemInput();if(['emoklore_en','emoklore_ja'].includes($('systemSelect').value))document.querySelectorAll('#gmContainer .gm-role').forEach(role=>role.value='DL')}previewSelectedStyle()})}
window.addEventListener('DOMContentLoaded',()=>{renderAsciiOptions();bindEvents();addGM();addPlayer();addPlayer();setTodayPlaceholder();updateCustomSystemInput();previewSelectedStyle()});
