const fontVariantMaps={
  sansBoldItalic:{upper:0x1D63C,lower:0x1D656,digit:0x1D7EC},sansBold:{upper:0x1D5D4,lower:0x1D5EE,digit:0x1D7EC},sansItalic:{upper:0x1D608,lower:0x1D622,digit:null},serifBoldItalic:{upper:0x1D468,lower:0x1D482,digit:0x1D7CE},serifBold:{upper:0x1D400,lower:0x1D41A,digit:0x1D7CE},serifItalic:{upper:0x1D434,lower:0x1D44E,digit:null,lowerExceptions:{h:'ℎ'}},
  smallCaps:{chars:{A:'ᴀ',B:'ʙ',C:'ᴄ',D:'ᴅ',E:'ᴇ',F:'ꜰ',G:'ɢ',H:'ʜ',I:'ɪ',J:'ᴊ',K:'ᴋ',L:'ʟ',M:'ᴍ',N:'ɴ',O:'ᴏ',P:'ᴘ',Q:'ꞯ',R:'ʀ',S:'ꜱ',T:'ᴛ',U:'ᴜ',V:'ᴠ',W:'ᴡ',X:'x',Y:'ʏ',Z:'ᴢ',a:'ᴀ',b:'ʙ',c:'ᴄ',d:'ᴅ',e:'ᴇ',f:'ꜰ',g:'ɢ',h:'ʜ',i:'ɪ',j:'ᴊ',k:'ᴋ',l:'ʟ',m:'ᴍ',n:'ɴ',o:'ᴏ',p:'ᴘ',q:'ꞯ',r:'ʀ',s:'ꜱ',t:'ᴛ',u:'ᴜ',v:'ᴠ',w:'ᴡ',x:'x',y:'ʏ',z:'ᴢ'}},typewriter:{upper:0x1D670,lower:0x1D68A,digit:0x1D7F6},modernSans:{upper:0x1D5A0,lower:0x1D5BA,digit:0x1D7E2}
};
const systemMaps={
  normal:{call_of_cthulhu:'Call of Cthulhu',coc:'CoC',coc6:'CoC6',coc7:'CoC7',new_coc:'新クトゥルフ神話TRPG',emoklore_en:'emoklore-trpg',emoklore_ja:'エモクロアTRPG',madamisu:'マーダーミステリー',shinobigami:'シノビガミ',insane:'インセイン',double_cross:'ダブルクロス The 3rd Edition',sword_world_25:'ソード・ワールド2.5',futari_sousa:'フタリソウサ',custom:'自由入力'},
  lower:{call_of_cthulhu:'ᴄᴀʟʟ ᴏꜰ ᴄᴛʜᴜʟʜᴜ',coc:'ᴄᴏᴄ',coc6:'ᴄᴏᴄ𝟨',coc7:'ᴄᴏᴄ𝟩',new_coc:'新クトゥルフ神話TRPG',emoklore_en:'emoklore-trpg',emoklore_ja:'エモクロアTRPG',madamisu:'マーダーミステリー',shinobigami:'シノビガミ',insane:'インセイン',double_cross:'ダブルクロス The 3rd Edition',sword_world_25:'ソード・ワールド2.5',futari_sousa:'フタリソウサ',custom:'自由入力'},
  bold:{call_of_cthulhu:'𝐂𝐚𝐥𝐥 𝐨𝐟 𝐂𝐭𝐡𝐮𝐥𝐡𝐮',coc:'𝐂𝐨𝐂',coc6:'𝐂𝐨𝐂𝟔',coc7:'𝐂𝐨𝐂𝟕',new_coc:'新クトゥルフ神話TRPG',emoklore_en:'emoklore-trpg',emoklore_ja:'エモクロアTRPG',madamisu:'マーダーミステリー',shinobigami:'シノビガミ',insane:'インセイン',double_cross:'ダブルクロス The 3rd Edition',sword_world_25:'ソード・ワールド2.5',futari_sousa:'フタリソウサ',custom:'自由入力'}
};
systemMaps.short=systemMaps.normal;
const protectedTokens=['探索者A','探索者B','PL名A','PL名B','KP名','KPC名','作者名','新クトゥルフ神話TRPG','エモクロアTRPG','emoklore-trpg','マーダーミステリー'];
function cp(ch,start,base){return base===null?ch:String.fromCodePoint(base+ch.charCodeAt(0)-start)}
function styleText(text,variant){const map=fontVariantMaps[variant];if(!map||variant==='plain')return text;return Array.from(text.normalize('NFKD')).map(ch=>{if(map.chars)return map.chars[ch]||ch;if(/[A-Z]/.test(ch))return cp(ch,65,map.upper);if(/[a-z]/.test(ch))return map.lowerExceptions?.[ch]||cp(ch,97,map.lower);if(/[0-9]/.test(ch))return cp(ch,48,map.digit);return ch}).join('')}
function styleTextPreservingSamples(text,variant){let t=text,marks=[];protectedTokens.forEach((token,i)=>{const marker=`__KEEP_${i}__`;marks.push([marker,token]);t=t.split(token).join(marker)});let styled=styleText(t,variant);marks.forEach(([marker,token])=>{styled=styled.split(styleText(marker,variant)).join(token).split(marker).join(token)});return styled}
function lineJoin(lines){return lines.join('\n').replace(/[ \t]+$/gm,'').replace(/\n{3,}/g,'\n\n').trim()}
function frameRoleLabel(role){return {KP:'ᴋᴘ',DL:'ᴅʟ',GM:'ɢᴍ','KPC/KP':'ᴋᴘᴄ/ᴋᴘ',SKP:'ꜱᴋᴘ','作/KP':'作/ᴋᴘ','進行':'進行'}[role]||String(role).toLowerCase()}
function playerLabel(x){const slot=x.slot==='自由'?'':x.slot;return slot&&x.ho?`${slot} ${x.ho}`:slot}
function formatFancyLabel(label){return String(label).replace(/^HO([0-9])$/i,(_,n)=>'𝐇𝐎'+String.fromCodePoint(0x1D7CE+Number(n))).replace(/^PC([0-9])$/i,(_,n)=>'𝐏𝐂'+String.fromCodePoint(0x1D7CE+Number(n))).replace(/^HO$/i,'𝐇𝐎').replace(/^PC$/i,'𝐏𝐂').replace(/^PL\/PC$/i,'𝐏𝐋/𝐏𝐂').replace(/^PC\/PL$/i,'𝐏𝐂/𝐏𝐋')}
function playerLines(data,format='pcpl'){return data.players.map(x=>{const label=playerLabel(x),colon=label?`${label}：`:'',space=label?`${label} `:'';if(format==='classic')return `${label?`${label}: `:''}${x.pc||'PC未入力'} / ${x.pl||'PL未入力'}`;if(format==='frame')return `${space}${x.pc||'PC未入力'} | ${x.pl||'PL未入力'}`;if(format==='plain-pipe')return `${x.pc||'PC未入力'} | ${x.pl||'PL未入力'}`;if(format==='emoklore-arrow')return `┗ ${space}${x.pc||'PC未入力'} | ${x.pl||'PL未入力'}`;if(format==='ho-dash')return `${label||'PC'}\n　　- ${x.pc||'PC未入力'} / ${x.pl||'PL未入力'}`;return `${colon}${x.pc||'PC未入力'} / ${x.pl||'PL未入力'}`})}
function gmLines(d,sep='：'){return d.gms.map(x=>`${x.role}${sep}${sep===':'?' ':''}${x.name}`)}
function withTail(lines,d,keys){keys.forEach(k=>{if(d[k])lines.push('',d[k])});return lineJoin(lines)}
function generateClassic(d){const l=[d.systemShort,`「${d.scenario||'シナリオ名'}」`,'',...gmLines(d,':')];if(d.players.length)l.push('','PC/PL',...playerLines(d,'classic'));return withTail(l,d,['result','quote','date','hashtags'])}
function generateMinimal(d){const l=[d.systemShort,`『${d.scenario||'シナリオ名'}』`,'',...gmLines(d)];if(d.players.length)l.push(...playerLines(d));return withTail(l,d,['result','hashtags'])}
function generateFrame(d){const l=['✦   ┈┈┈┈┈┈┈┈┈┈┈┈   ✦',`      ${d.systemShort}`,`   　　${d.scenario||'シナリオ名'}`,''];d.gms.forEach(x=>l.push(`  　${frameRoleLabel(x.role)}┊${x.name}`));if(d.players.length)l.push('  　ᴘᴄ┊ᴘʟ',...playerLines(d,'frame').map(x=>`  　${x}`));if(d.result)l.push(`  　── ${d.result} ──`);if(d.quote)l.push('',`　 ${d.quote}`);l.push('✦   ┈┈┈┈┈┈┈┈┈┈┈┈   ✦');return withTail(l,d,['hashtags'])}
function generateAsteriskFrame(d){const border='✼••┈┈••✼••┈┈••✼',l=[border,`    ${d.systemShort}`,`　${d.scenario||'シナリオ名'}`,border];d.gms.forEach(x=>l.push(`${x.role}: ${x.name}`));if(d.players.length)l.push('','PC/PL',...playerLines(d,'classic'));l.push('',d.result||'END');return lineJoin(l)}
function generateFancy(d){const l=['⟡.·*.····························⟡.·*.',` ${d.systemBold}`,`　     ◤ ${d.scenario||'シナリオ名'} ◢`,''];l.push(...d.gms.map(x=>` ${x.role} ${x.name}`));d.players.forEach(x=>{const label=formatFancyLabel(playerLabel(x)||'PC');l.push(` ${label}`,` ┗ ${x.pc||'PC未入力'} | ${x.pl||'PL未入力'}`)});return withTail(l,d,['result','quote','hashtags'])}
function generateBlock(d){const l=[`▮     ${d.systemLower}     ▮`,'',`  『  ${d.scenario||'シナリオ名'}  』`,''];d.gms.forEach(x=>l.push(`${frameRoleLabel(x.role)} ${x.name}`));if(d.players.length){l.push('ᴘʟᴘᴄ');playerLines(d,'frame').forEach(x=>l.push(`   ${x}`))}return withTail(l,d,['quote','hashtags'])}
function generateHOFocus(d){const l=[d.systemBold,`『 ${d.scenario||'シナリオ名'} 』`,'',...gmLines(d,' '),'𝐏𝐂/𝐏𝐋',...playerLines(d,'ho-dash')];if(d.result)l.push('',`-　${d.result}　-`);return withTail(l,d,['quote','date','hashtags'])}
function normalizeKpcPairName(name){const t=String(name||'').trim();if(!t||t==='KP名')return 'KPC名 | KP名';const parts=t.replaceAll('｜','/').replaceAll('|','/').split('/').map(x=>x.trim()).filter(Boolean);return parts.length>1?parts.join(' | '):t}
function generateKpcPair(d){const l=[d.systemLower,`【 ${d.scenario||'タイトル'} 】`,''];if(d.gms.length)l.push('| ᴋᴘᴄ・ᴋᴘ',`  ${normalizeKpcPairName(d.gms[0].name)}`);if(d.players.length)l.push('| ᴘᴄ・ᴘʟ',`  ${playerLines(d,'plain-pipe')[0]}`);return withTail(l,d,['quote','date','hashtags'])}
function generateEmoklore(d){const l=['✧',`   ${d.systemShort}`,`     「 ${d.scenario||'シナリオ名'} 」`];if(d.date)l.push(` 　　    Date. ${d.date}`);l.push('');d.gms.forEach(x=>l.push(`${x.role} ${x.name}`));if(d.players.length)l.push('PcᐟPL',...playerLines(d,'emoklore-arrow'));if(d.result)l.push('',`✧ ${d.result}`);return withTail(l,d,['quote','hashtags'])}
function generateWideTitle(d){const l=[d.systemShort,`◤　${d.scenario||'シナリオ名'}　◢`,'',...gmLines(d)];if(d.players.length)l.push('𝗣𝗟/𝗣𝗖',...playerLines(d));return withTail(l,d,['result','quote','date','hashtags'])}
function generateZigzag(d){const b='◢◤◢◤◢◤◢◤◢◤◢',l=[b,`　${d.systemShort}`,`　　　${d.scenario||'タイトル'}`,'',b];d.gms.forEach(x=>l.push(`${x.role} ${x.name}`));if(d.players.length){l.push('PC/PL');d.players.forEach(x=>l.push(playerLabel(x)||'PC',`  - ${x.pc||'PC未入力'} / ${x.pl||'PL未入力'}`))}if(d.result)l.push('',`- ${d.result} -`);return withTail(l,d,['quote','date','hashtags'])}
function generateCornerFrame(d){const l=['◤￣￣￣￣￣￣￣￣￣',` ${d.systemShort}`,`        ${d.scenario||'シナリオ名'}`,'','＿＿＿＿＿＿＿＿＿◢'];d.gms.forEach(x=>l.push(`${x.role}: ${x.name}`));if(d.players.length)l.push('','PC/PL',...d.players.map(x=>` ${x.pc||'PC未入力'} / ${x.pl||'PL未入力'}`));return withTail(l,d,['result','quote','date','hashtags'])}
function generateTriangleHeading(d){const l=[`▸ ${d.systemShort}`,'',`- ${d.scenario||'シナリオ名'} -`,''];d.gms.forEach(x=>l.push(`▸ ${x.role}: ${x.name}`));if(d.players.length){const first=d.players[0];l.push(`▸ PC/PL: ${first.pc||'PC未入力'} / ${first.pl||'PL未入力'}`);d.players.slice(1).forEach(x=>l.push(`               ${x.pc||'PC未入力'} / ${x.pl||'PL未入力'}`))}if(d.result)l.push('',`▸ ${d.result}`);return withTail(l,d,['quote','date','hashtags'])}
function generateScenarioClear(d){const l=['⧉ ᴄᴏᴄ 𝟨ᴛʜ',`.　　${d.scenario||'Title'}`];if(d.author)l.push(`.　　　　${d.author}`);l.push('');d.gms.forEach(x=>l.push(`｜${frameRoleLabel(x.role)}`,`　${x.name}`,''));if(d.players.length){l.push('｜ᴘᴄ・ᴘʟ');d.players.forEach(x=>l.push(`　${x.pc||'Tansakusha'} / ${x.pl||'PL name'}`));l.push('')}l.push('　- ꜱᴄᴇɴᴀʀɪᴏ ᴄʟᴇᴀʀ -');return withTail(l,d,['quote','date','hashtags'])}
function generateHandwrittenTitle(d){const border='┈┈┈┈┈┈┈┈┈',l=['𝐜𝐚𝐥𝐥 𝐨𝐟 𝐜𝐭𝐡𝐮𝐥𝐡𝐮',`⌜ ${d.scenario||'TITLE'} ⌟`,border];if(d.gms.length){l.push('✧𝐊𝐏');d.gms.forEach(x=>l.push(`  ▹${x.name}`));l.push('')}if(d.players.length){l.push('✧𝐏𝐋');d.players.forEach(x=>{const label=formatFancyLabel(playerLabel(x)||'PC');l.push(`  ▹${label} ${x.ho||'HO name'}   ${x.pc||'Character Name'} / ${x.pl||'PL Name'}`)});l.push('')}l.push(`✧𝐄𝐍𝐃 ${d.result||'title'}`,`${border}ᝰ✍︎ ꙳⋆`);return withTail(l,d,['quote','date','hashtags'])}
function generateDoubleLine(d){const b='══════════════',l=[b,`   ${d.systemShort}`,`　${d.scenario||'TITLE'}`,b,''];d.gms.forEach(x=>l.push(`${frameRoleLabel(x.role)}：${x.name}`));d.players.forEach(x=>{const label=playerLabel(x)||'ʜᴏ';l.push(`${label.toLowerCase()} ${x.ho||'HO name'}`,`　　 ${x.pc||'Character Name'} / ${x.pl||'PL Name'}`)});return withTail(l,d,['result','quote','date','hashtags'])}
function generateRibbonTitle(d){const l=[d.systemBold,`　‧₊˚ ୨  ${d.scenario||'title'}  ୧ ˚₊`];if(d.gms.length){l.push('𝗞𝗣…');d.gms.forEach(x=>l.push(`　${x.name}`));l.push('')}if(d.players.length){l.push('𝗣𝗖/𝗣𝗟…');d.players.forEach(x=>l.push(`　${x.pc||'Character Name'} / ${x.pl||'PL Name'}`))}return withTail(l,d,['result','quote','date','hashtags'])}
const templates={classic:generateClassic,minimal:generateMinimal,frame:generateFrame,'asterisk-frame':generateAsteriskFrame,fancy:generateFancy,block:generateBlock,'ho-focus':generateHOFocus,'kpc-pair':generateKpcPair,emoklore:generateEmoklore,'wide-title':generateWideTitle,zigzag:generateZigzag,'corner-frame':generateCornerFrame,'triangle-heading':generateTriangleHeading,'scenario-clear':generateScenarioClear,'handwritten-title':generateHandwrittenTitle,'double-line':generateDoubleLine,'ribbon-title':generateRibbonTitle};
window.ReportParser={systemMaps,templates,styleTextPreservingSamples,lineJoin};
