window.CHARAMEMO_I18N = {
  ja: {
    tagKoma: "駒JSON入力",
    tagTxt: "いあきゃらTXT入力",
    tagCopy: "CCFOLIA用コピー",
    usage: "使い方",
    shortcut: "ショートカット",
    usageTitle: "使い方",
    usageStep1: "「キャラ出力▶︎ココフォリア駒出力」からコピーした駒JSONを貼り付けます。",
    usageStep2: "いあきゃらのテキスト出力を貼り付けるか、txtファイルを開きます。",
    usageStep3: "必要に応じて生成オプションを切り替え、キャラメモを編集します。",
    usageStep4: "「生成駒JSONデータをコピー」からCCFOLIAへ貼り付けます。",
    shortcutTitle: "ショートカット",
    shortcutEsc: "使い方・ショートカットパネルを閉じる",
    shortcutCopy: "生成駒JSONデータをコピー",
    shortcutReset: "入力データを削除",
    shortcutTheme: "ライト/ナイトモードを切り替え",
    title: "いあキャラMEMOジェネレータ",
    description: "CCFOLIA駒JSONと、いあきゃらのテキスト出力を読み込み、プロフィール・所持品・バックストーリー・メモを整理して、CCFOLIA用のキャラメモ入り駒JSONを再生成します。",
    panelJson: "1. CCFOLIA駒JSON",
    jsonLabel: "キャラ出力▶︎ココフォリア駒出力 からコピー&ペースト",
    panelTxt: "2. いあきゃらTXT",
    openTxt: "txtファイルを開く",
    clearTxt: "TXTクリア",
    panelOptions: "3. 生成オプション",
    optWeapons: "戦闘・武器・防具を含める",
    optItems: "所持品を含める",
    optKnowledge: "新たに得た知識・経験を含める",
    optMemo: "TXT内メモを含める",
    optPalette: "チャットパレット整形",
    summaryTitle: "解析キャラクター概要",
    editMemo: "4. キャラメモ編集",
    generateMemo: "TXTからメモ生成",
    copyMemo: "メモコピー",
    memoPreview: "5. キャラメモ プレビュー",
    palettePreview: "6. チャットパレットプレビュー",
    copyPalette: "パレットコピー",
    jsonOutput: "7. 生成済み駒JSON",
    copyGeneratedJson: "生成駒JSONデータをコピー",
    deleteData: "データを削除"
  },
  en: {
    tagKoma: "Koma JSON Input",
    tagTxt: "Iachara TXT Input",
    tagCopy: "Copy for CCFOLIA",
    usage: "Guide",
    shortcut: "Shortcuts",
    usageTitle: "Guide",
    usageStep1: "Paste the CCFOLIA character JSON exported from the character output menu.",
    usageStep2: "Paste the Iachara text export or open a .txt file.",
    usageStep3: "Adjust generation options and edit the character memo as needed.",
    usageStep4: "Copy the generated Koma JSON and paste it into CCFOLIA.",
    shortcutTitle: "Shortcuts",
    shortcutEsc: "Close Guide / Shortcut panels",
    shortcutCopy: "Copy generated Koma JSON",
    shortcutReset: "Delete input data",
    shortcutTheme: "Toggle light/night mode",
    title: "Iachara MEMO Generator",
    description: "Generate CCFOLIA character JSON with organized memo content from CCFOLIA Koma JSON and Iachara text exports.",
    panelJson: "1. CCFOLIA Koma JSON",
    jsonLabel: "Paste JSON exported from CCFOLIA Koma output",
    panelTxt: "2. Iachara TXT",
    openTxt: "Open txt file",
    clearTxt: "Clear TXT",
    panelOptions: "3. Generation Options",
    optWeapons: "Include combat / weapons / armor",
    optItems: "Include items",
    optKnowledge: "Include gained knowledge / experience",
    optMemo: "Include TXT memo",
    optPalette: "Format chat palette",
    summaryTitle: "Parsed Character Summary",
    editMemo: "4. Edit Character Memo",
    generateMemo: "Generate memo from TXT",
    copyMemo: "Copy memo",
    memoPreview: "5. Character Memo Preview",
    palettePreview: "6. Chat Palette Preview",
    copyPalette: "Copy palette",
    jsonOutput: "7. Generated Koma JSON",
    copyGeneratedJson: "Copy generated Koma JSON",
    deleteData: "Delete data"
  }
};
